#pmake: all build serv remote os_linux cpu_386 tcp x86
host_CPU = 386
host_OS = linux

os = linux
srv = tcp
cpu = x86
which = SERVER

extra_objs = $(remote_objs) peloader.obj

!include $(trap_dir)/master.mif
 

