fp_model        = i87
exe             = wf387
form            = dos4g
__386__         =
!ifdef __UNIX__
share_objs      = ../obj387/
!else
share_objs      = ..\obj387\
!endif
japan_objs      =

!include        ../makego.mif
