#pmake: all build large cpu_i86 os_win
#
# contl.lib -- large memory-model CONTAINER library for Windows
#
processor  = i86
system     = windows
model      = l
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
