#pmake: build os_dos cpu_386
# makefile for GRAPH3S.LIB

host_CPU = 386
host_OS = dos

libname =       graph3s
model =         -ms -3s -d_NEC_PC -d__STACK
module =        $[&s
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -3s -ms -i"../inc" -d_MODEL=_SMALL -d_386 -d_NEC_PC
_NEC_PC =       1

!include ../graphics.mif
