#pmake: os_qnx cpu_386 flat
#
# plibmt3r -- 32-bit 3r PLIB multi-thread library
#
host_cpu = 386

suffix = mt3r
target_system = qnx
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/lib$(suffix).mif
!include $(plusplus_dir)/mklib.mif
