#pmake: build large cpu_i86 os_osi
#
# strgl.lib -- large memory-model STRING library
#
processor  = 086
system     = generic
model      = ml
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
