#pmake: all build os_nt cpu_386

host_OS         = nt
host_CPU        = 386

fp_model        = i87
exe             = wf387
form            = nt
__386__         =
share_objs      = ..\obj387\

!include        ..\makego.mif
