#pmake: all build os_nt cpu_386

host_OS         = nt
host_CPU        = 386

fp_model        = i87
exe             = wf387
form            = nt
__386__         =
!ifdef __UNIX__
share_objs      = ../obj387/
!else
share_objs      = ..\obj387\
!endif

!include        ../makego.mif
