#pmake: build huge cpu_i86 os_osi
#
# strgh.lib -- huge memory-model STRING library
#
processor  = 086
system     = generic
model      = mh
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
