#pmake: all build cpu_i86 os_os2
host_CPU = i86
host_OS = os2

os = pm
build_target = os2_pm
model=l
compiler = comp286
plat_inc=$(lang_root)\h\os21x;
xflags=-zu-s
wpi_lib=wpi_pm16
wlib_opt = /p=32

!include ..\makefile

#guifdlg.obj : $(guidir)\ui\c\guifdlg.c
#           $($(compiler)) $(guidir)\ui\c\guifdlg.c /d__OS2__ $(cflags)

