#pmake: build os_nt cpu_386

host_OS             = nt
host_CPU            = 386

proj_name          = ddk
include_dir        = ../../include/ddk
root_dir           = ../..
lib_dir            = ../../lib/ddk
what_to_build      = libs

!include ../../master.mif
