#pmake: build flat cpu_386 os_nt
#
# plib3s -- 32-bit 3s PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = static
fs_registration = yes
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
