#pmake: all build os_os2 cpu_386

host_OS         = os2
host_CPU        = 386

fp_model        = c
exe             = wf386
form            = os2v2
__386__         =
oshdrs          = $(inc_dirs_sys_os2)
share_objs      = ..\obj386\

!include        ..\makego.mif
