xcopy \doc\gs\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\cl\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\gui\snaps\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\cg\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\fg\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\pg\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\wd\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\lr\ge\*.bmp o:\cproj\cdoc\freeze11\bmp
xcopy \doc\isv\*.bmp o:\cproj\cdoc\freeze11\bmp
