call ..\setup11
call ..\mkit isv %1
call ..\mkit cbooks %1
call ..\mkit fbooks %1
call ..\mkit c_readme %1
call ..\mkit f_readme %1
call ..\mkit cguide %1
call ..\mkit clr %1
call ..\mkit ddespy %1
call ..\mkit drnt %1
call ..\mkit drwatcom %1
call ..\mkit editor %1
call ..\mkit heapwalk %1
call ..\mkit ide %1
call ..\mkit lguide %1
call ..\mkit pguide %1
call ..\mkit resacc %1
call ..\mkit resdlg %1
call ..\mkit resedt %1
call ..\mkit resimg %1
call ..\mkit resmnu %1
call ..\mkit resstr %1
call ..\mkit rescomp %1
call ..\mkit spy %1
call ..\mkit tools %1
call ..\mkit wbrw %1
call ..\mkit wd %1
call ..\mkit wprof %1
call ..\mkit zoom %1
call ..\mkit wccerrs %1
call ..\mkit wpperrs %1
call ..\mkit wlnkerrs %1
call ..\mkit wrcerrs %1
call ..\mkit clib %1
call ..\mkit clibnt %1
call ..\mkit cpplib %1
call ..\mkit f77graph %1
call ..\mkit f77lr %1
call ..\mkit fpguide %1
call ..\mkit ftools %1
call ..\mkit fuguide %1
call ..\mkit wfcerrs %1
call ..\mkit cmix %1
call ..\mkit fmix %1
call ..\mkit wjcerrs %1
