#pmake: trap remote os_nt cpu_386 tcp axp
host_CPU = axp
host_OS = nt

os = nt
srv = tcp
cpu = axp
which = TRAP

extra_objs = $(remote_objs)
extra_libs = $(lang_root)/libaxp/nt/wsock32.lib

!include $(trap_dir)/master.mif
