#pmake: build medium cpu_i86 os_osi
#
# iostm.lib -- medium memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
define_deps_include = $(cpplib_dir)/iostream/deps.mif
!include $(cpplib_dir)/mklib.mif
