#pmake: all build large cpu_i86 os_osi
#
# iostl.lib -- large memory-model IOSTREAM library
#
host_cpu = i86

suffix = l
target_system = generic
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
