#pmake: all os_dos cpu_386

host_OS         = dos
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flib7
model           = s
fp_model        = i87
is_NEC          =

!include ../master.mif
