#pmake: build flat cpu_386 os_os2 dynamic debug
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
cpplib_release = 0
subdir     = mf_rmtd.dll
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
