#pmake: all build serv remote os_nt cpu_386 nov x86
host_CPU = 386
host_OS = nt

gui = 1
os = nt
srv = nov
cpu = x86
which = SERVER

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)/lib386/nt/wsock32.lib

!include $(trap_dir)/master.mif
