#pmake: all build serv remote os_nt cpu_386 nov x86

gui = 1
os = nt
srv = nov
cpu = x86

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)\lib386\nt\wsock32.lib

!include $(trap_dir)\serv.mif
