#pmake: nobuild os_nt cpu_axp

host_os       = nt
host_cpu      = axp

proj_name     = base
root_dir      = ..
include_dir   = $(root_dir)/include
lib_dir       = $(root_dir)/lib
what_to_build = libs

!include ../master.mif
