#pmake: build os_qnx cpu_i86
# makefile for GRAPHS.LIB

libname =       graphs
model =         -ms -d_SUPERVGA -bt=QNX
module =        $[&
cdecl =         _loadds
fard =
_386 =
_qnx =          q
asm_cmd =       wasm
asm_flags =     -zq -ms -i..\inc -d_MODEL=_SMALL

!include ../graphics.mif
