#pmake: build trap remote os_win cpu_i86 cpu_386 par x86
host_CPU = i86
host_OS = win

os = win
srv = par
cpu = x86
which = TRAP

extra_objs = $(remote_objs) pardos.obj

!include $(trap_dir)/master.mif
