.* all sysvars documented in script_tso.txt and some others sorted alfabetically
.* created with WATCOM Script/GML V4.0
.* all found system symbols of form SYS* ( * == up to 6 letters ) are shown here
.* for device ps without specifying another layout
.* as result of several runs with tsys07.gml ( ~3 h run for every first letter )
.* some longer variables which are documented are shown too
.* some single char values are shown in decimal and hex


.ty SYSAD = &SYSAD
.ty SYSADEVEN = &SYSADEVEN
.ty SYSADODD = &SYSADODD
.ty SYSAMP = &SYSAMP
.ty AMP = &AMP
.ty SYSAPAGE = &SYSAPAGE
.ty SYSAUTHOR = &SYSAUTHOR

.ty SYSBC = &SYSBC
.ty SYSBE = &SYSBE
.ty SYSBFONTS = &SYSBFONTS
.ty SYSBM = &SYSBM
.ty SYSBO = &SYSBO
.ty SYSBS = &SYSBS c2d(sysbs)=&'c2d(&sysbs) c2x(sysbs)=&'c2x(&sysbs)
.ty SYSBX = &SYSBX
.ty SYSBXCHAR = &SYSBXCHAR

.ty SYSCC = &SYSCC
.ty SYSCCC = &SYSCCC
.ty SYSCD = &SYSCD
.ty SYSCDCOUNT = &SYSCDCOUNT
.ty SYSCL = &SYSCL
.ty SYSCO = &SYSCO
.ty SYSCONT = &SYSCONT c2d(syscont)=&'c2d(&syscont) c2x(syscont)=&'c2x(&syscont)
.ty SYSCP = &SYSCP
.ty SYSCPAGES = &SYSCPAGES
.ty SYSCPC = &SYSCPC
.ty SYSCPI = &SYSCPI
.'ty SYSCW = &SYSCW

.ty SYSDATE = &SYSDATE
.ty SYSDAYOFM = &SYSDAYOFM
.ty SYSDAYOFW = &SYSDAYOFW
.ty SYSDAYOFY = &SYSDAYOFY
.ty SYSDFONTS = &SYSDFONTS
.ty SYSDHSET = &SYSDHSET
.ty SYSDOCNUM = &SYSDOCNUM
.ty SYSDPAGE = &SYSDPAGE
.ty SYSDUPLEX = &SYSDUPLEX

.ty SYSENV = &SYSENV
.ty SYSERRCONT = &SYSERRCONT

.ty SYSFB = &SYSFB
.ty SYSFBC = &SYSFBC
.ty SYSFBF = &SYSFBF
.ty SYSFILE = &SYSFILE
.ty SYSFK = &SYSFK
.ty SYSFKC = &SYSFKC
.ty SYSFLNEST = &SYSFLNEST
.ty SYSFM = &SYSFM
.ty SYSFN = &SYSFN
.ty SYSFNAM = &SYSFNAM
.ty SYSFNC = &SYSFNC
.ty SYSFNCOUNT = &SYSFNCOUNT
.ty SYSFNUM = &SYSFNUM
.ty SYSFONTS = &SYSFONTS
.ty SYSFS = &SYSFS

.ty SYSGML = &SYSGML
.ty GML = &GML
.ty SYSGUTTER = &SYSGUTTER

.ty SYSHI = &SYSHI
.ty SYSHM = &SYSHM
.ty SYSHN = &SYSHN
.ty SYSHNC = &SYSHNC
.ty SYSHOUR = &SYSHOUR
.ty SYSHS = &SYSHS
.ty SYSHY = &SYSHY
.ty SYSHYC = &SYSHYC
.ty SYSHYPH = &SYSHYPH
.ty SYSHYRULES = &SYSHYRULES

.ty SYSIN = &SYSIN
.ty SYSINR = &SYSINR
.ty SYSIR = &SYSIR
.ty SYSIXJ = &SYSIXJ
.ty SYSIXREF = &SYSIXREF

.ty SYSJU = &SYSJU

.ty SYSLAYOUT = &SYSLAYOUT
.ty SYSLC = &SYSLC
.ty SYSLI = &SYSLI
.ty SYSLINB = &SYSLINB
.ty SYSLINE = &SYSLINE
.ty SYSLL = &SYSLL
.ty SYSLNUM = &SYSLNUM
.ty SYSLPI = &SYSLPI
.ty SYSLS = &SYSLS
.ty SYSLST = &SYSLST

.ty SYSMC = &SYSMC
.ty SYSMCS = &SYSMCS
.ty SYSMEMBER = &SYSMEMBER
.ty SYSMINUTE = &SYSMINUTE
.ty SYSMONTH = &SYSMONTH

.ty SYSNODEID = &SYSNODEID

.ty SYSOF = &SYSOF
.ty SYSOFFLINE = &SYSOFFLINE
.ty SYSONLINE = &SYSONLINE
.ty SYSOOC = &SYSOOC
.ty SYSOUT = &SYSOUT

.ty SYSPAGE = &SYSPAGE
.ty SYSPAGED = &SYSPAGED
.ty SYSPAGELM = &SYSPAGELM
.ty SYSPAGERM = &SYSPAGERM
.ty SYSPARM = &SYSPARM
.ty SYSPASSNO = &SYSPASSNO
.ty SYSPASSOF = &SYSPASSOF
.ty SYSPDAYOFW = &SYSPDAYOFW
.ty SYSPDEV = &SYSPDEV
.ty SYSPGNUMA = &SYSPGNUMA
.ty SYSPGNUMC = &SYSPGNUMC
.ty SYSPGNUMR = &SYSPGNUMR
.ty SYSPI = &SYSPI
.ty SYSPIX = &SYSPIX
.ty SYSPL = &SYSPL
.ty SYSPLS = &SYSPLS
.ty SYSPMONTH = &SYSPMONTH
.ty SYSPN = &SYSPN
.ty SYSPPAGE = &SYSPPAGE
.ty SYSPRS = &SYSPRS
.ty SYSPRT = &SYSPRT
.ty SYSPS = &SYSPS
.ty SYSPW = &SYSPW
.ty SYSPYEAR = &SYSPYEAR

.ty SYSRB = &SYSRB c2d(sysrb)=&'c2d(&sysrb) c2x(sysrb)=&'c2x(&sysrb)
.ty SYSRECNO = &SYSRECNO
.ty SYSRESH = &SYSRESH
.ty SYSRESV = &SYSRESV
.ty SYSRET = &SYSRET
.ty SYSRETCODE = &SYSRETCODE
.ty SYSRMNEST = &SYSRMNEST

.ty SYSSC = &SYSSC
.ty SYSSCREEN = &SYSSCREEN
.ty SYSSEC = &SYSSEC
.ty SYSSECOND = &SYSSECOND
.ty SYSSEQNO = &SYSSEQNO
.ty SYSSKCOND = &SYSSKCOND
.ty SYSSL = &SYSSL
.ty SYSSPCOND = &SYSSPCOND
.ty SYSSTITLE = &SYSSTITLE
.ty SYSSU = &SYSSU
.ty SYSSYS = &SYSSYS

.ty SYSTAB = &SYSTAB c2d(systab)=&'c2d(&systab) c2x(systab)=&'c2x(&systab)
.ty SYSTB = &SYSTB c2d(systb)=&'c2d(&systb) c2x(systb)=&'c2x(&systb)
.ty SYSTERMT = &SYSTERMT
.ty SYSTIME = &SYSTIME
.ty SYSTISET = &SYSTISET
.ty SYSTITLE = &SYSTITLE
.ty SYSTM = &SYSTM

.ty SYSUDIGN = &SYSUDIGN
.ty SYSUDINC = &SYSUDINC
.ty SYSUSERID = &SYSUSERID

.ty SYSVERSION = &SYSVERSION

.ty SYSWD = &SYSWD
.ty SYSXTEXT = &SYSXTEXT
.ty SYSYEAR = &SYSYEAR

