.co on
.ju off
Preliminary DL/GL tests:
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eOL.
.in 10 -10
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eOL.
.in
:SL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eSL.
.in 10 -10
:SL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eSL.
.in
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eUL.
.in 10 -10
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eUL.
.in
:P.Text used with tag P --
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:PC.Text used with tag PC --
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:DL.
:LP.outer DL list text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:DL.
:LP.outer DL list text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eDL.
:eDL.
:GL.
:LP.outer GL list text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:GL.
:LP.outer GL list text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eGL.
:eGL.
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eOL
:eOL
:eOL
:SL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:SL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eSL
:eSL
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:eUL
:eUL
:eUL
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:LP.outer list text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LI.outer list item text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:OL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:LP.inner OL text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LI.OL list item text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LP.inner OL text 2 -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eOL.
:SL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:LP.inner SL text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LI.SL list item text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eSL.
:UL.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 1.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 2.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 3.
:LI.LI with enough text to show the right margin even on the outermost level of indentation 4.
:LP.inner UL text text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LI.UL list item text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:LI.UL list item text 2 -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eUL.
:DL.
:LP.inner DL text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eDL.
:GL.
:LP.inner GL text -- 
Nesting tag LP inside each of a definition list and a glossary list which in turn were embedded 
in an ordered list, simple list, or unordered list does not use the left_indent of a definition 
list or a glossary list in which it is embedded. Further testing showed that an ordered list, 
simple list or unordered list embedded in the same outer list behaved the same way. And LI in the 
embedded  ordered list, simple list or unordered list showed the same positioning (in the case of 
the ordered and unordered list this was the position of the item number or the bullet). In 
effect, the LP behaves as if it were an LI in a simple list.
:eGL.
:eOL.

