#
# This file will not be processed by pmake, because it has #notpmake instead
# of #pmake. This is because it doesn't build yet completely for i86. You can
# do wmake in this dir to try the build.

#notpmake: all build os_dos cpu_i86 bdiff
host_CPU    = i86
host_OS     = dos

!include ..\master.mif


