#pmake: all build medium cpu_i86 os_osi
processor  = i86
system     = generic
model      = m
linkage    = static
subdir     = bcsd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
