#pmake: debug flat cpu_386 os_os2
#
# strg3r.lib -- register based 32-bit STRING library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
release_cpplib  = 0
fs_registration = yes
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
