#pmake: debug flat cpu_386 os_os2
#
# strg3r.lib -- register based 32-bit STRING library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
cpplib_release  = 0
fs_registration = yes
define_library_include = $(cpplib_dir)/string/string.mif
define_deps_include = $(cpplib_dir)/string/deps.mif
!include $(cpplib_dir)/mklib.mif
