#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp CONTAINER library
#
host_cpu = axp

suffix = nt
target_system = ntaxp
uncompressed=1
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/libaxp$(suffix).mif
!include $(plusplus_dir)/mklib.mif
