#pmake: all build cpu_386 os_os2
host_CPU = 386
host_OS = os2

os = pm
build_target = os2_pm
model=f
compiler = comp386
plat_inc=$(inc_dirs_sys_os2);
xflags=-s
wpi_lib=wpi_os2f
wlib_opt = -p=32

!include ../guiwin.mif
