#pmake: build small cpu_i86 os_osi
#
# conts.lib -- small memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = ms
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(cpplib_dir)/mklib.mif
