#include "about.msg"
#include "tooltips.msg"

pick( VI_BROWSE_MSG,
      "Please select a folder.",
      "Please select a folder." )

pick( VI_LANG_FIRST,    "C",        "C" )
pick( VI_LANG_LANG0,    "C++",      "C++" )
pick( VI_LANG_LANG1,    "Fortran",  "Fortran" )
pick( VI_LANG_LANG2,    "Java",     "Java" )
pick( VI_LANG_LANG3,    "SQL",      "SQL" )
pick( VI_LANG_LANG4,    "Batch",    "Batch" )
pick( VI_LANG_LANG5,    "Basic",    "Basic" )
pick( VI_LANG_LANG6,    "Perl",     "Perl" )
pick( VI_LANG_LANG7,    "HTML",     "HTML" )
pick( VI_LANG_LANG8,    "WML",      "WML" )
pick( VI_LANG_LANG9,    "GML",      "GML" )
pick( VI_LANG_LANG10,   "DBTest",   "DBTest" )
pick( VI_LANG_LANG11,   "Makefile", "Makefile" )
pick( VI_LANG_LAST,     "Resource", "Resource" )
