#pmake: all build trap remote os_nt cpu_386 nov x86
host_cpu = 386

os = nt
srv = nov
cpu = x86

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)\lib386\nt\wsock32.lib

!include $(trap_dir)\trap.mif
