#pmake: all build trap remote os_nt cpu_386 nov x86
host_CPU = 386
host_OS = nt

os = nt
srv = nov
cpu = x86
which = TRAP

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)/lib386/nt/wsock32.lib

!include $(trap_dir)/master.mif
