#pmake: all build serv remote os_dos cpu_i86 cpu_386 tcp x86

os = dos
srv = tcp
cpu = x86
dos_large_model = 1

extra_objs = $(remote_objs)
extra_incs = $(%owroot)\contrib\wattcp\inc
extra_libs = $(%owroot)\contrib\wattcp\lib\wattcpwl.lib

!include $(trap_dir)\serv.mif

