#pmake: all build compact cpu_i86 os_win
#
# contc.lib -- compact memory-model CONTAINER library for Windows
#
processor  = i86
system     = windows
model      = c
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
