#pmake: all build compact cpu_i86 os_win
#
# contc.lib -- compact memory-model CONTAINER library for Windows
#
host_cpu = i86

suffix = c
target_system = windows
text = -zW
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
