#pmake: build os_dos cpu_386
# makefile for GRAPH3R.LIB

host_CPU = 386
host_OS = dos

libname =       graph3r
model =         -ms -3r -d_SUPERVGA
module =        $[&r
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -3r -ms -fo=$[&.obj -i"../inc" -d_MODEL=_SMALL -d_386

!include ../graphics.mif
