#pmake: all build medium cpu_i86 os_win
#
# cplx7m.lib -- medium memory-model COMPLEX library fpi for Windows
#
processor  = i87
system     = windows
model      = m
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
