#pmake: build large cpu_i86 os_osi
#
# contl.lib -- large memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = ml
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(cpplib_dir)/mklib.mif
