#pmake: all build large cpu_i86 os_osi
#
# contl.lib -- large memory-model CONTAINER library
#
processor  = i86
system     = generic
model      = l
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
