#pmake: build large cpu_i86 os_win
#
# cplx7l.lib -- large memory-model COMPLEX library fpi for Windows
#
processor  = 087
system     = windows
model      = ml
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
