#pmake: no_build1 flat register 32bit inline winnt iX86 rtdll os_nt cpu_386
component=wrtlib
processor=387
model=mf
subdir=mf_r
system=winnt
convention=register
!include $(rtdll)/master.mif
!include ../objs.mif
!include $(rtdll)/mkdll.mif
