#pmake: all build compact cpu_i86 os_osi
#
# contc.lib -- compact memory-model CONTAINER library
#
host_cpu = i86

suffix = c
target_system = generic
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
