#pmake: all os_nt cpu_PPC

host_OS         = NT
host_CPU        = PPC

# FORTRAN project definitions
lib_name        = flib
model           =
fp_model        =
is_MT           =
is_DLL          =

!include ..\master.mif
