#pmake: build medium cpu_i86 os_win
#
# plibm -- 16-bit medium memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = mm
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
