#pmake: all build medium cpu_i86 os_win
#
# plibm -- 16-bit medium memory-model PLIB for Windows
#
processor  = i86
system     = windows
model      = m
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
