#pmake: all build medium cpu_i86 os_osi
#
# strgm.lib -- medium memory-model STRING library
#
processor  = i86
system     = generic
model      = m
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
