#pmake: build medium cpu_i86 os_osi
#
# strgm.lib -- medium memory-model STRING library
#
processor  = 086
system     = generic
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
define_deps_include = $(cpplib_dir)/string/deps.mif
!include $(cpplib_dir)/mklib.mif
