#pmake: all build trap remote os_dos cpu_i86 cpu_386 ser x86
host_cpu = i86

os = dos
srv = ser
cpu = x86

extra_objs = $(remote_objs) serint.obj serdos.obj busywait.obj

!include $(trap_dir)/trap.mif
