#pmake: build trap remote os_dos cpu_i86 cpu_386 ser x86
host_CPU = i86
host_OS = dos

os = dos
srv = ser
cpu = x86
which = TRAP

extra_objs = $(remote_objs) serint.obj serdos.obj busywait.obj

!include $(trap_dir)/master.mif
