#pmake: all build large cpu_i86 os_win
#
# contl.lib -- large memory-model CONTAINER library for Windows
#
host_cpu = i86

suffix = l
target_system = windows
text = -zW
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
