#pmake: all build os_os2 cpu_386

targos          = os2386

!ifdef prebuild
!include $(posix_dir)/mif/bld_cmds.mif
!else
!include $(posix_dir)/mif/commands.mif
!endif

!include $(posix_dir)/mif/makeall.mif
