#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp STRING library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
uncompressed = 1
define_library_include = $(cpplib_dir)/string/string.mif
define_deps_include = $(cpplib_dir)/string/deps.mif
!include $(cpplib_dir)/mklib.mif
