#pmake: serv remote os_nt cpu_386 tcp axp
host_CPU = axp
host_OS = nt

gui = 1
os = nt
srv = tcp
cpu = axp
which = SERVER

extra_objs = $(remote_objs)
extra_libs = $(lang_root)/libaxp/nt/wsock32.lib

!include $(trap_dir)/master.mif
