#pmake: all build os_nov cpu_386

host_OS         = nov
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flib7s
model           = f
fp_model        = i87
is_MT           =
is_stack        =

!include ..\master.mif
