#pmake: os_qnx cpu_386 flat
#
# contmt3r.lib -- register based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = qnx
model      = ms
convention = register
linkage    = static
mthreaded  = 1
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(cpplib_dir)/mklib.mif
