#pmake: all build trap remote os_nt cpu_i86 cpu_386 tcp x86
host_cpu = 386

os = nt
srv = tcp
cpu = x86

extra_objs = $(remote_objs)
extra_libs = $(lang_root)/lib386/nt/wsock32.lib

!include $(trap_dir)/trap.mif
