#pmake: debug flat cpu_386 os_os2
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
cpplib_release  = 0
fs_registration = yes
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
