#pmake: all build os_win cpu_i86
#
# WATCOM Presentation Graphics (PGCHART.LIB)
#

libname =       chartw
model =         -ml -zW
module =        $[&
cdecl =         _loadds
fard =
_386 =

!include ../pgchart.mif
