#pmake: build flat cpu_386 os_nt dynamic
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = dynamic
mthreaded  = 1
subdir     = mf_smt.dll
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
