#pmake: all build flat cpu_386 os_osi os_dos os_linux
processor  = 386
system     = generic
model      = f
convention = stack
linkage    = static
subdir     = 3s
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
