#pmake: all build huge cpu_i86 os_osi
#
# plibh -- 16-bit huge memory-model PLIB
#
processor  = i86
system     = generic
model      = h
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
