#pmake: build huge cpu_i86 os_osi
#
# plibh -- 16-bit huge memory-model PLIB
#
processor  = 086
system     = generic
model      = mh
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
