#pmake: os_dos cpu_i86 target_i86

host_OS         = dos
host_CPU        = i86

# FORTRAN project definitions
use_ems         =

# code generator project definitions
target_CPU      = i86

!include ../master.mif
