.sr CharTest = 'Character Manipulation Functions'
.sr Math = 'Mathematical Functions'
.sr Trig = 'Trigonometric Functions'
.sr Hyper = 'Hyperbolic Functions'
.sr StrIo = 'Stream I/O Functions'
.sr String = 'String Functions'
.sr Jstring = 'Kanji String Functions'
.sr Multibyte = 'Multibyte Character Functions'
.sr Wide = 'Wide Character Functions'
.sr Copy = 'Copying Functions'
.sr Jcopy = 'Kanji Copying Functions'
.sr Concats = 'Concatenation Functions'
.sr Jconcats = 'Kanji Concatenation Functions'
.sr Compare = 'Comparison Functions'
.sr Jcompare = 'Kanji Comparison Functions'
.sr Search = 'Search Functions'
.sr Jsearch = 'Kanji Search Functions'
.sr Memory = 'Memory Allocation'
.sr Conversion = 'Conversion Functions'
.sr TimeFunc = 'Time Functions'
.if '&machsys' eq 'FOX' .do begin
.sr OsIo = 'DOS I/O Functions'
.sr DosFunc = 'DOS Functions'
.do end
.el .do begin
.sr OsIo = '&machsys I/O Functions'
.sr DosFunc = '&machsys Functions'
.do end
.sr WinIo = 'Default Windowing Functions'
.sr OS2Func = 'OS/2 Functions'
.sr NTFunc = 'Win32 Functions'
.sr TNTFunc = 'PharLap TNT Functions'
.sr BiosFunc = 'BIOS Functions'
.if '&machsys' eq 'FOX' .do begin
.sr OsInt = 'DOS Interrupts'
.do end
.el .do begin
.sr OsInt = '&machsys Interrupts'
.do end
.sr CpuInt = '8086 Interrupts'
.sr KbIo = 'Console I/O'
.sr PortIo = 'Port I/O'
.sr Process = 'Process Functions'
.sr Errs = 'Error Handling'
.sr FileOp = 'File Operations'
.sr Direct = 'Directory Functions'
.sr Rotate = 'Rotate Functions'
.sr Interrupt = 'Interrupt Functions'
.sr Parsing = 'Filename Parsing Functions'
.sr TSR = 'Terminate and Stay Resident'
.sr Locale = 'Locale Functions'
.sr Heap = 'Heap Functions'
