call crun mempty
call crun mtoint
call crun mfromint
call crun mpaddb
call crun mpaddd
call crun mpaddsb
call crun mpaddsw
call crun mpaddusb
call crun mpaddusw
call crun mpaddw
call crun mpand
call crun mpandn
call crun mpckssdw
call crun mpcksswb
call crun mpckuswb
call crun mpcmpeqb
call crun mpcmpeqd
call crun mpcmpeqw
call crun mpcmpgtb
call crun mpcmpgtd
call crun mpcmpgtw
call crun mpmaddwd
call crun mpmulhw
call crun mpmullw
call crun mpor
call crun mpslld
call crun mpslldi
call crun mpsllq
call crun mpsllqi
call crun mpsllw
call crun mpsllwi
call crun mpsrad
call crun mpsradi
call crun mpsraw
call crun mpsrawi
call crun mpsrld
call crun mpsrldi
call crun mpsrlq
call crun mpsrlqi
call crun mpsrlw
call crun mpsrlwi
call crun mpsubb
call crun mpsubd
call crun mpsubsb
call crun mpsubsw
call crun mpsubusb
call crun mpsubusw
call crun mpsubw
call crun mpxor
call crun mupckhbw
call crun mupckhdq
call crun mupckhwd
call crun mupcklbw
call crun mupckldq
call crun mupcklwd
