#pmake: build os_win cpu_i86 necdos
#
# Open Watcom Debugger makefile for Windows
#

host_OS=win
host_CPU=i86
display=char

machine = nec

sysobjs =   &
    wininit.obj &
    winchk.obj &
    wincmd.obj &
    winfilio.obj &
    winlkup.obj &
    winscrn.obj

!include ../../master.mif
