#pmake: all build large cpu_i86 os_os2
processor  = i86
system     = os2
model      = l
convention =
linkage    = static
mthreaded  = 1
subdir     = os2mt
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
