#pmake: build compact cpu_i86 os_win
#
# strgc.lib -- compact memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
