#pmake: all os_dos cpu_386

host_OS         = dos
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flibs
model           = s
fp_model        = c
is_stack        =
is_NEC          =

!include ../master.mif
