#pmake: all build os_dos cpu_386
#
# WATCOM Presentation Graphics (PGCHART.LIB)
#

host_CPU = 386
host_OS = dos

libname =       chart3s
model =         -ms -3s
module =        $[&s
cdecl =
fard =
_386 =          386

!include ../pgchart.mif
