#pmake: all build flat cpu_386 os_os2 dynamic
host_CPU = 386

suffix = mt3r
subdir = os23rmt.dll
linkage = dynamic
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
