#pmake: build os_nt cpu_386

host_CPU        = 386
host_OS         = nt

proj_name       = directx
include_dir     = ../../include/directx
lib_dir         = ../../lib/directx

!include ../../master.mif
