#pmake: build huge cpu_i86 os_osi
#
# cplx7h.lib -- huge memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mh
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
