#pmake: all build huge cpu_i86 os_osi
#
# cplx7h.lib -- huge memory-model COMPLEX library fpi
#
processor  = i87
system     = generic
model      = h
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
