#pmake: os_nt cpu_AXP target_axp

host_OS         = nt
host_CPU        = axp

# FORTRAN project definitions
lib_name        = flib
model           =
fp_model        =
is_MT           =
is_DLL          =

!include ..\master.mif
