#pmake: all build flat cpu_386 os_osi os_dos os_linux
#
# plib3s -- 32-bit 3s PLIB
#
host_cpu = 386

suffix = 3s
target_system = generic
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/lib32$(suffix).mif
!include $(plusplus_dir)/mklib.mif
