#pmake: os_qnx cpu_386 flat

host_cpu  = 386
fs_prefix = q
suffix    = mt3r
subdir    = 3rmt
target_lib = $(prefix)$(suffix).lib
production_lib = lib386
define_library_include = $(plusplus_cpplib_dir)\plib.mif

!include $(plusplus_dir)\mrglib.mif
