#pmake: build os_nt cpu_386

host_OS             = nt

proj_name          = gl
include_dir        = ../../include/gl
root_include_dir   = ../../include
lib_dir            = ../../lib
what_to_build      = headers

!include ../../master.mif
