#pmake: build flat cpu_386 os_nt
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = static
subdir     = mf_s
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
