#pmake: build flat cpu_386 os_nt dynamic
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
subdir     = mf_rmtd.dll
cpplib_release = 0
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
