#pmake: trap remote os_os2 cpu_i86 nov
host_CPU = i86

os  = os2
srv = nov
cpu = x86

extra_objs = $(remote_objs) novos2.obj
extra_incs = $(nwos2dir)
extra_libs = $(nwos2dir)/ipxcalls.lib $(nwos2dir)/nwcallsp.lib $(nwos2dir)/spxcalls.lib

!include $(trap_dir)/trap.mif
