#pmake: build trap remote os_dos cpu_i86 cpu_386 winl x86
host_CPU = i86
host_OS = dos

os = dos
srv = win
cpu = x86
which = TRAP

extra_objs = $(remote_objs)

extra_c_flags_winlink = -3

!include $(trap_dir)/master.mif
