@echo off
CALL FMT C_README pass 2
CALL FMT CGUIDE   pass 3
CALL FMT CGUIDEQ  pass 3
CALL FMT PGUIDE   pass 2
CALL FMT CTOOLS   pass 2
CALL FMT GUITOOL  pass 3
CALL FMT WDBG	  pass 3
CALL FMT CLIB_DOS pass 2
rem PSSTRIP <CLIB_DOS.PS >CLIB_V1.PS 1-566 1177-1211
rem PSSTRIP <CLIB_DOS.PS >CLIB_V2.PS 1-22 567-1211
rem CALL FMT CLIB_NT  pass 2
CALL FMT CLIB_QNX pass 2
CALL FMT CPPLIB   pass 2
CALL FMT LGUIDE   pass 3
CALL FMT C	  pass 2
CALL FMT F_README pass 2
CALL FMT FUGUIDE  pass 2
CALL FMT FPGUIDE  pass 2
CALL FMT FTOOLS   pass 2
CALL FMT F77LR	  pass 2
CALL FMT F77GRAPH pass 2
