VERSION = _UI
model = f
rational=1

guilib  = $(guidir)\ui\guidos$(model).lib
uilib   = $(uidir)\dos\uilib$(model).lib
#!ifndef gui_10_0
reslib = $(wres_dir)\lib\wres$(model).lib
#!else
#reslib = clib3r
#!endif

!include ../setup.mif
