VERSION = _UI
model = f
rational=1

guilib  = $(guidir)/ui/dos386/gui.lib
guiinc  = $(guidir)/ui/dos386
uilib   = $(uidir)/dos/dos386/ui.lib
#!ifndef gui_10_0
reslib = $(wres_dir)\lib\wres$(model).lib
#!else
#reslib = clib3r
#!endif

!include ../setup.mif
