#pmake: all os_pp cpu_386

host_OS         = pp
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flibs
model           = f
fp_model        = c
is_stack        =

!include ..\master.mif
