#pmake: build os_nt cpu_386

host_OS             = nt

proj_name          = ddk
include_dir        = ../../include/ddk
root_dir           = ../..
lib_dir            = ../../lib/ddk
what_to_build      = headers

!include ../../master.mif
