#pmake: nomodel cpu_axp os_nt
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
mthreaded    = 1
subdir       = _smt
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
