/****************************************************************************
*
*                            Open Watcom Project
*
*    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
*
*  ========================================================================
*
*    This file contains Original Code and/or Modifications of Original
*    Code as defined in and that are subject to the Sybase Open Watcom
*    Public License version 1.0 (the 'License'). You may not use this file
*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
*    provided with the Original Code and Modifications, and is also
*    available at www.sybase.com/developer/opensource.
*
*    The Original Code and all software distributed under the License are
*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
*    NON-INFRINGEMENT. Please see the License for the specific language
*    governing rights and limitations under the License.
*
*  ========================================================================
*
* Description:  WHEN YOU FIGURE OUT WHAT THIS FILE DOES, PLEASE
*               DESCRIBE IT HERE!
*
****************************************************************************/


//
// IFNAMES   : intrinsic function name table
//

#include "ftnstd.h"

char    *IFNames[] = {
    "ABS",
    "ACOS",
    "AIMAG",
    "AINT",
    "ALGAMA",
    "ALLOCATED",
    "ALOG",
    "ALOG10",
    "AMAX0",
    "AMAX1",
    "AMIN0",
    "AMIN1",
    "AMOD",
    "ANINT",
    "ASIN",
    "ATAN",
    "ATAN2",
    "BTEST",
    "CABS",
    "CCOS",
    "CDABS",
    "CDCOS",
    "CDEXP",
    "CDLOG",
    "CDSIN",
    "CDSQRT",
    "CEXP",
    "CHAR",
    "CLOG",
    "CMPLX",
    "CONJG",
    "COS",
    "COSH",
    "COTAN",
    "CQABS",
    "CQCOS",
    "CQEXP",
    "CQLOG",
    "CQSIN",
    "CQSQRT",
    "CSIN",
    "CSQRT",
    "DABS",
    "DACOS",
    "DASIN",
    "DATAN",
    "DATAN2",
    "DBLE",
    "DCMPLX",
    "DCONJG",
    "DCOS",
    "DCOSH",
    "DCOTAN",
    "DDIM",
    "DERF",
    "DERFC",
    "DEXP",
    "DFLOAT",
    "DGAMMA",
    "DIM",
    "DIMAG",
    "DINT",
    "DLGAMA",
    "DLOG",
    "DLOG10",
    "DMAX1",
    "DMIN1",
    "DMOD",
    "DNINT",
    "DPROD",
    "DREAL",
    "DSIGN",
    "DSIN",
    "DSINH",
    "DSQRT",
    "DTAN",
    "DTANH",
    "ERF",
    "ERFC",
    "EXP",
    "FLOAT",
    "GAMMA",
    "HFIX",
    "I1ABS",
    "I1AND",
    "I1BCHNG",
    "I1BCLR",
    "I1BSET",
    "I1BTEST",
    "I1DIM",
    "I1EOR",
    "I1LSHIFT",
    "I1MAX0",
    "I1MIN0",
    "I1MOD",
    "I1NOT",
    "I1OR",
    "I1RSHIFT",
    "I1SHA",
    "I1SHC",
    "I1SHFT",
    "I1SHL",
    "I1SIGN",
    "I2ABS",
    "I2AND",
    "I2BCHNG",
    "I2BCLR",
    "I2BSET",
    "I2BTEST",
    "I2DIM",
    "I2EOR",
    "I2LSHIFT",
    "I2MAX0",
    "I2MIN0",
    "I2MOD",
    "I2NOT",
    "I2OR",
    "I2RSHIFT",
    "I2SHA",
    "I2SHC",
    "I2SHFT",
    "I2SHL",
    "I2SIGN",
    "IABS",
    "IAND",
    "IBCHNG",
    "IBCLR",
    "IBSET",
    "ICHAR",
    "IDIM",
    "IDINT",
    "IDNINT",
    "IEOR",
    "IFIX",
    "IMAG",
    "INDEX",
    "INT",
    "IOR",
    "IQINT",
    "IQNINT",
    "ISHA",
    "ISHC",
    "ISHFT",
    "ISHL",
    "ISIGN",
    "ISIZEOF",
    "LEN",
    "LENTRIM",
    "LGAMMA",
    "LGE",
    "LGT",
    "LLE",
    "LLT",
    "LOC",
    "LOG",
    "LOG10",
    "LSHIFT",
    "MAX",
    "MAX0",
    "MAX1",
    "MIN",
    "MIN0",
    "MIN1",
    "MOD",
    "NINT",
    "NOT",
    "QABS",
    "QACOS",
    "QASIN",
    "QATAN",
    "QATAN2",
    "QCMPLX",
    "QCONJG",
    "QCOS",
    "QCOSH",
    "QCOTAN",
    "QDIM",
    "QERF",
    "QERFC",
    "QEXP",
    "QEXT",
    "QGAMMA",
    "QIMAG",
    "QINT",
    "QLGAMA",
    "QLOG",
    "QLOG10",
    "QMAX1",
    "QMIN1",
    "QMOD",
    "QNINT",
    "QPROD",
    "QSIGN",
    "QSIN",
    "QSINH",
    "QSQRT",
    "QTAN",
    "QTANH",
    "REAL",
    "RSHIFT",
    "SIGN",
    "SIN",
    "SINH",
    "SNGL",
    "SQRT",
    "TAN",
    "TANH",
    "VOLATILE",

    NULL
};
