#pmake/75: build1 flat register 32bit calls winnt iX86 rtdll os_nt cpu_386 cpplib profile
component=cpplib
processor=386
model=mf
subdir=mf_r
system=winnt
convention=register
profile=1
!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
