#pmake: all build small cpu_i86 os_win
processor  = i86
system     = windows
model      = s
linkage    = static
subdir     = wscsd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
