#pmake: all build flat cpu_386 os_osi
#
# contmt3s.lib -- stack based multi-thread 32-bit CONTAINER library
#
host_cpu = 386

suffix = mt3s
target_system = generic
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib$(suffix).mif
!include $(plusplus_dir)/mklib.mif
