cflags = -bt=OS2 -mf-fpc-oxt-zq-w4 -i=$(uidir)\h;$(trmem_dir) -fo=$[& /of+

!include ..\main.mif

linkit : .PROCEDURE
        @%append $(lnk) system os2v2
        @%append $(lnk) name $(name).exe
        @%append $(lnk) lib $(uidir)\os2\uilibf.lib
