#pmake: build medium cpu_i86 os_osi
#
# cplx7m.lib -- medium memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mm
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
