#pmake: build small cpu_i86 os_osi
#
# cplx7s.lib -- small memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
define_deps_include = $(cpplib_dir)/complex/deps.mif
!include $(cpplib_dir)/mklib.mif
