#pmake: all build flat cpu_386 os_nt
processor  = 386
system     = winnt
model      = f
convention = stack
linkage    = static
subdir     = nt3s
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
