call ..\setup11
call mk isv ipftarg
call mk c_readme ipftarg
call mk f_readme ipftarg
call mk clr ipftarg
call mk ide ipftarg
call mk wbrw ipftarg
call mk wprof ipftarg
call mk cguide ipftarg
call mk fuguide ipftarg
call mk pguide ipftarg
call mk fpguide ipftarg
call mk lguide ipftarg
call mk tools ipftarg
call mk wd ipftarg
call mk rescomp ipftarg
call mk clib ipftarg
call mk f77graph ipftarg
call mk cpplib ipftarg
call mk wccerrs ipftarg
call mk wpperrs ipftarg
call mk ftools ipftarg
call mk f77lr ipftarg
call mk wfcerrs ipftarg
call mk cmix ipftarg
call mk fmix ipftarg
