#pmake/75: build2 small register 32bit calls os2 iX86 rtdll os_os2 cpu_386 cpplib
component=cpplib
processor=386
model=ms
subdir=ms_r
system=os2
convention=register
!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
