#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp IOSTREAM library
#
host_cpu = axp

suffix = mt
target_system = ntaxp
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
define_target_include = $(plusplus_dir)/libaxp$(suffix).mif
!include $(plusplus_dir)/mklib.mif
