#pmake: all build trap remote os_os2 cpu_i86 cpu_386 nmp x86

os  = os2v2
srv = nmp
cpu = x86

extra_objs = $(remote_objs) nmpos22.obj
extra_libs = $(%os2tkroot)\lib\os2386.lib

!include $(trap_dir)\trap.mif
