#pmake: all build flat cpu_386 os_os2
processor  = 386
system     = os2
model      = f
convention = stack
linkage    = static
mthreaded  = 1
subdir     = os23smt
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
