#pmake: all build os_qnx cpu_386
# makefile for GRAPH3R.LIB

libname =       graph3r
model =         /ms /3r /d_SUPERVGA /bt=QNX
module =        $[&r
cdecl =
fard =
_386 =          386
_qnx =          q
asm_cmd =       wasm
asm_flags =     -3r -ms -i..\inc\ -d_QNX -d_MODEL=_SMALL -d_386

!include ..\graphics.mif
