#pmake: all build flat cpu_386 os_osi os_dos os_linux
#
# cont3r.lib -- register based 32-bit CONTAINER library
#
suffix = 3r
target_system = generic
production_lib = lib386
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib32$(suffix).mif
!include $(plusplus_dir)/mklib.mif
