#pmake: all build large cpu_i86 os_win
processor  = i86
system     = windows
model      = l
linkage    = static
subdir     = wbcbd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
