@echo off
rm -rf wise
md wise
rm mkwise.log
call unzipit clib_a16
call unzipit clib_d16
call unzipit clib_o16
call unzipit clib_o32
call unzipit clib_w16
call unzipit clib_w32
call unzipit cm_clib_a16
call unzipit cm_clib_a32
call unzipit cm_clib_d16
call unzipit cm_clib_d32
call unzipit cm_clib_hdr
call unzipit cm_clib_n32
call unzipit cm_clib_o16
call unzipit cm_clib_o32
call unzipit cm_clib_w16
call unzipit cm_clib_w32
call unzipit cm_core_all
call unzipit cm_core_dos
call unzipit cm_core_doswin
call unzipit cm_core_nt
call unzipit cm_core_os2
call unzipit cm_core_win
call unzipit cm_dbg_all
call unzipit cm_dbg_dos
call unzipit cm_dbg_dosos2
call unzipit cm_dbg_doswin
call unzipit cm_dbg_misc1
call unzipit cm_dbg_misc2
call unzipit cm_dbg_net
call unzipit cm_dbg_nt
call unzipit cm_dbg_os2
call unzipit cm_dbg_os2nt
call unzipit cm_dbg_win
call unzipit cm_ide_all
call unzipit cm_ide_nt
call unzipit cm_ide_os2
call unzipit cm_ide_dos
call unzipit cm_ide_win
call unzipit cm_hlp_dos
call unzipit cm_hlp_nt
call unzipit cm_hlp_os2
call unzipit cm_hlp_win
call unzipit cm_plib_a16
call unzipit cm_plib_a32
call unzipit cm_plib_o32
call unzipit cm_plib_w32
call unzipit core_all
call unzipit core_doswin
call unzipit core_nt
call unzipit core_os2
call unzipit cpp_doswin
call unzipit cpp_nt
call unzipit cpp_os2
call unzipit c_doswin
call unzipit c_nt
call unzipit c_os2
call unzipit fc_doswin
call unzipit fc_hlp_dos
call unzipit fc_hlp_nt
call unzipit fc_hlp_os2
call unzipit fc_hlp_win
call unzipit fc_nt
call unzipit fc_os2
call unzipit flib_d16
call unzipit flib_d32
call unzipit flib_n32
call unzipit flib_o16
call unzipit flib_o32
call unzipit flib_w16
call unzipit flib_w32
call unzipit hlp_dos
call unzipit hlp_nt
call unzipit hlp_os2
call unzipit hlp_win
call unzipit plib_a16
call unzipit plib_a32
call unzipit plib_hdr
call unzipit plib_o16
call unzipit plib_o32
call unzipit plib_w16
call unzipit plib_w32
call unzipit cm_samples
call unzipit clib_samples
call unzipit plib_samples
call unzipit win_samples
call unzipit ide_samples
call unzipit f_samples
call unzipit misc_src
call unzipit os2api
call unzipit w32api
call unzipit ext_causeway
call unzipit ext_dos4gw
call unzipit ext_dos32a
call unzipit ext_pmodew
echo All done!

