fp_model        = i87
exe             = watfor87
form            = dos
!ifdef __UNIX__
share_objs      = ../obj87/
!else
share_objs      = ..\obj87\
!endif
japan_objs      =

!include        ../makego.mif
