#pmake: all os_os2 cpu_i86

host_OS         = os2
host_CPU        = i86

# FORTRAN project definitions
lib_name        = flibmtl
model           = l
fp_model        = c
is_MT           =

!include ..\master.mif
