#pmake: all build small cpu_i86 os_win
#
# plibs -- 16-bit small memory-model PLIB for Windows
#
host_cpu = i86

suffix = s
target_system = windows
text = -zW
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
