#pmake: all build small cpu_i86 os_win
#
# plibs -- 16-bit small memory-model PLIB for Windows
#
processor  = i86
system     = windows
model      = s
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
