#pmake: trap remote os_nt cpu_386 nov axp
host_CPU = axp
host_OS = nt

os = nt
srv = nov
cpu = axp
which = TRAP

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)/libaxp/nt/wsock32.lib

!include $(trap_dir)/master.mif
