#pmake: all build flat cpu_386 os_nt dynamic
processor  = 386
system     = winnt
model      = f
convention = register
linkage    = dynamic
mthreaded  = 1
subdir     = nt3rmt.dll
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
