#pmake: build os_dos cpu_386
# makefile for GRAPH3R.LIB

libname =       graph3r
model =         -ms -3r -d_NEC_PC
module =        $[&r
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -3r -ms -i..\inc -d_MODEL=_SMALL -d_386 -d_NEC_PC
_NEC_PC =       1

!include ../graphics.mif
