#pmake: all build flat cpu_386 os_nt dynamic profile
processor  = 386
system     = winnt
model      = f
convention = register
linkage    = dynamic
mthreaded  = 1
profile    = 1
subdir     = nt3rmtp.dll
release_lib_page_size = -p=32
debug_lib_page_size = -p=128
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
