#pmake: all build flat cpu_386 os_nt dynamic profile
host_CPU = 386

suffix = mt3r
subdir = nt3rmtp.dll
linkage = dynamic
profile = 1
release_lib_page_size = -p=32
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
