cflags = -bt=DOS -mf-fpc-oxt-zq-w4 -i=$(uidir)\h;$(trmem_dir) -fo=$[& /of+

!include ..\main.mif

linkit : .PROCEDURE
        @%append $(lnk) system dos4g
        @%append $(lnk) name $(name).exe
        @%append $(lnk) lib $(uidir)\dos\uilibf.lib
