#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# strg3r.lib -- register based 32-bit STRING library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
