#pmake: all build compact cpu_i86 os_win
processor  = i86
system     = windows
model      = c
linkage    = static
subdir     = wscbd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
