#pmake: all build flat cpu_386 os_nt dynamic
host_CPU = 386

suffix = mt3s
subdir = nt3smt.dll
linkage = dynamic
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
