#pmake: build serv remote os_win cpu_i86 cpu_386 net x86
host_cpu = i86
host_OS = win

gui = 1
os = win
srv = net
cpu = x86
which = SERVER

extra_objs = $(remote_objs)

!include $(trap_dir)/master.mif
