@echo off
set da_cmplr=%1
if [%da_cmplr%]==[] set da_cmplr=wcc386
echo %da_cmplr% inline assembler test
call dotest 486      %da_cmplr%
call dotest adc      %da_cmplr%
call dotest add      %da_cmplr%
call dotest admodes  %da_cmplr%
call dotest admodes1 %da_cmplr%
call dotest admodes2 %da_cmplr%
call dotest admodes3 %da_cmplr%
call dotest admodes4 %da_cmplr%
call dotest admodes5 %da_cmplr%
call dotest admodes6 %da_cmplr%
call dotest amodes   %da_cmplr%
call dotest amodes1  %da_cmplr%
call dotest amodes2  %da_cmplr%
call dotest amodes3  %da_cmplr%
call dotest amodes4  %da_cmplr%
call dotest amodes5  %da_cmplr%
call dotest amodes6  %da_cmplr%
call dotest and      %da_cmplr%
call dotest bt       %da_cmplr%
call dotest bug      %da_cmplr%
call dotest cmp      %da_cmplr%
call dotest cmpx     %da_cmplr%
call dotest dec      %da_cmplr%
call dotest div      %da_cmplr%
call dotest dmodes1  %da_cmplr%
call dotest dmodes2  %da_cmplr%
call dotest dmodes3  %da_cmplr%
call dotest dmodes4  %da_cmplr%
call dotest dmodes5  %da_cmplr%
call dotest dmodes6  %da_cmplr%
call dotest enter    %da_cmplr%
call dotest fadd     %da_cmplr%
call dotest fcom     %da_cmplr%
call dotest fdiv     %da_cmplr%
call dotest fld      %da_cmplr%
call dotest fmul     %da_cmplr%
call dotest fp       %da_cmplr%
call dotest fpmisc   %da_cmplr%
call dotest fpmisc2  %da_cmplr%
call dotest fsub     %da_cmplr%
call dotest fucom    %da_cmplr%
call dotest idiv     %da_cmplr%
call dotest imul     %da_cmplr%
call dotest in       %da_cmplr%
call dotest inc      %da_cmplr%
call dotest lea      %da_cmplr%
call dotest lod      %da_cmplr%
call dotest lxs      %da_cmplr%
call dotest misc     %da_cmplr%
call dotest misc2    %da_cmplr%
call dotest modes    %da_cmplr%
call dotest modes1   %da_cmplr%
call dotest modes2   %da_cmplr%
call dotest modes3   %da_cmplr%
call dotest modes4   %da_cmplr%
call dotest modes5   %da_cmplr%
call dotest modes6   %da_cmplr%
call dotest mov      %da_cmplr%
call dotest mov2     %da_cmplr%
call dotest movs     %da_cmplr%
call dotest movx     %da_cmplr%
call dotest mul      %da_cmplr%
call dotest neg      %da_cmplr%
call dotest not      %da_cmplr%
call dotest or       %da_cmplr%
call dotest out      %da_cmplr%
call dotest outs     %da_cmplr%
call dotest pop      %da_cmplr%
call dotest rcl      %da_cmplr%
call dotest sal      %da_cmplr%
call dotest sbb      %da_cmplr%
call dotest scas     %da_cmplr%
call dotest setcc    %da_cmplr%
call dotest shld     %da_cmplr%
call dotest sub      %da_cmplr%
call dotest test     %da_cmplr%
call dotest xadd     %da_cmplr%
call dotest xchg     %da_cmplr%
call dotest xor      %da_cmplr%
