mkdir %DEVDIR%\nwsdk
mkdir %DEVDIR%\posix
mkdir %DEVDIR%\cpp
mkdir %DEVDIR%\vi
mkdir %DEVDIR%\idebatch
mkdir %DEVDIR%\sdk
mkdir %DEVDIR%\windows
mkdir %DEVDIR%\wstub
mkdir %DEVDIR%\c
mkdir %DEVDIR%\chkmouse
mkdir %DEVDIR%\clib
mkdir %DEVDIR%\cmdedit
mkdir %DEVDIR%\codegen
mkdir %DEVDIR%\emu
mkdir %DEVDIR%\emu86
mkdir %DEVDIR%\pgchart
mkdir %DEVDIR%\graphlib
mkdir %DEVDIR%\hdr
mkdir %DEVDIR%\wpack
mkdir %DEVDIR%\install
mkdir %DEVDIR%\hlp
mkdir %DEVDIR%\womp
mkdir %DEVDIR%\wbed
mkdir %DEVDIR%\wdisasm
mkdir %DEVDIR%\wl
mkdir %DEVDIR%\wlib
mkdir %DEVDIR%\wmake
mkdir %DEVDIR%\wprof
mkdir %DEVDIR%\wsample
mkdir %DEVDIR%\wstrip
mkdir %DEVDIR%\wtouch
mkdir %DEVDIR%\wv
mkdir %DEVDIR%\altsym
mkdir %DEVDIR%\f77
mkdir %DEVDIR%\misc
mkdir %DEVDIR%\uiforms
mkdir %DEVDIR%\bdiff
mkdir %DEVDIR%\src
mkdir %DEVDIR%\win386
mkdir %DEVDIR%\xmem
mkdir %DEVDIR%\gui
mkdir %DEVDIR%\aui
mkdir %DEVDIR%\techinfo
mkdir %DEVDIR%\watcom
mkdir %DEVDIR%\ui
mkdir %DEVDIR%\os220
mkdir %DEVDIR%\wasm
mkdir %DEVDIR%\plusplus
mkdir %DEVDIR%\dwarf
mkdir %DEVDIR%\wclass
mkdir %DEVDIR%\browser
mkdir %DEVDIR%\fmrbin
mkdir %DEVDIR%\binnt
mkdir %DEVDIR%\bin
mkdir %DEVDIR%\binp
mkdir %DEVDIR%\binp\dll
mkdir %DEVDIR%\qnx
mkdir %DEVDIR%\win
mkdir %DEVDIR%\nlm
mkdir %DEVDIR%\pen
mkdir %DEVDIR%\nt
