#!/bin/sh
#do some sanity checks here before we start creating gobs of directories
if [ -z "$RELROOT" -o -z "$DEFREL" ]; then
  echo The RELROOT and DEFREL environment variables need to be set!
  exit
fi
mkdir -p $RELROOT/$DEFREL
mkdir -p $RELROOT/$DEFREL/n98bw
mkdir -p $RELROOT/$DEFREL/binl
mkdir -p $RELROOT/$DEFREL/binnt
mkdir -p $RELROOT/$DEFREL/binp
mkdir -p $RELROOT/$DEFREL/binw
mkdir -p $RELROOT/$DEFREL/eddat
mkdir -p $RELROOT/$DEFREL/h
mkdir -p $RELROOT/$DEFREL/qnx
mkdir -p $RELROOT/$DEFREL/qnx/binq
mkdir -p $RELROOT/$DEFREL/qnx/binq/wd
mkdir -p $RELROOT/$DEFREL/qnx/sym
mkdir -p $RELROOT/$DEFREL/qnx/sym/wd
mkdir -p $RELROOT/$DEFREL/qnx/tix
mkdir -p $RELROOT/$DEFREL/qnx/watcom
mkdir -p $RELROOT/$DEFREL/qnx/watcom/wd
mkdir -p $RELROOT/$DEFREL/h/win
mkdir -p $RELROOT/$DEFREL/h/nt
mkdir -p $RELROOT/$DEFREL/h/nt/GL
mkdir -p $RELROOT/$DEFREL/h/os2
mkdir -p $RELROOT/$DEFREL/h/os2/arpa
mkdir -p $RELROOT/$DEFREL/h/os2/machine
mkdir -p $RELROOT/$DEFREL/h/os2/net
mkdir -p $RELROOT/$DEFREL/h/os2/netinet
mkdir -p $RELROOT/$DEFREL/h/os2/protocol
mkdir -p $RELROOT/$DEFREL/h/os2/sys
mkdir -p $RELROOT/$DEFREL/h/os2/GL
mkdir -p $RELROOT/$DEFREL/h/os21x
mkdir -p $RELROOT/$DEFREL/qh
mkdir -p $RELROOT/$DEFREL/qh/sys
mkdir -p $RELROOT/$DEFREL/lh
mkdir -p $RELROOT/$DEFREL/lh/arpa
mkdir -p $RELROOT/$DEFREL/lh/netinet
mkdir -p $RELROOT/$DEFREL/lh/sys
mkdir -p $RELROOT/$DEFREL/lib286
mkdir -p $RELROOT/$DEFREL/lib386
mkdir -p $RELROOT/$DEFREL/nlm
mkdir -p $RELROOT/$DEFREL/samples
mkdir -p $RELROOT/$DEFREL/src
mkdir -p $RELROOT/$DEFREL/binnt/rtdll
mkdir -p $RELROOT/$DEFREL/binp/dll
mkdir -p $RELROOT/$DEFREL/binp/help
mkdir -p $RELROOT/$DEFREL/h/sys
mkdir -p $RELROOT/$DEFREL/lib286/dos
mkdir -p $RELROOT/$DEFREL/lib286/os2
mkdir -p $RELROOT/$DEFREL/lib286/win
mkdir -p $RELROOT/$DEFREL/lib286/qnx
mkdir -p $RELROOT/$DEFREL/lib386/dos
mkdir -p $RELROOT/$DEFREL/lib386/netware
mkdir -p $RELROOT/$DEFREL/lib386/nt
mkdir -p $RELROOT/$DEFREL/lib386/os2
mkdir -p $RELROOT/$DEFREL/lib386/win
mkdir -p $RELROOT/$DEFREL/lib386/qnx
mkdir -p $RELROOT/$DEFREL/lib386/linux
mkdir -p $RELROOT/$DEFREL/libaxp
mkdir -p $RELROOT/$DEFREL/libaxp/nt
mkdir -p $RELROOT/$DEFREL/samples/clibexam
mkdir -p $RELROOT/$DEFREL/samples/cplbexam
mkdir -p $RELROOT/$DEFREL/samples/dll
mkdir -p $RELROOT/$DEFREL/samples/goodies
mkdir -p $RELROOT/$DEFREL/samples/ide
mkdir -p $RELROOT/$DEFREL/samples/os2
mkdir -p $RELROOT/$DEFREL/samples/win
mkdir -p $RELROOT/$DEFREL/samples/clibexam/kanji
mkdir -p $RELROOT/$DEFREL/samples/clibexam/test
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/complex
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/contain
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/fstream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/ios
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/iostream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/string
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/strstrea
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/complex/friend
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/complex/pubfun
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/complex/relfun
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/complex/relop
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/fstream/fstream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/fstream/ifstream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/fstream/ofstream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/iostream/iostream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/iostream/istream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/iostream/ostream
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/string/friend
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/string/pubfun
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/strstrea/istrstre
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/strstrea/ostrstre
mkdir -p $RELROOT/$DEFREL/samples/cplbexam/strstrea/strstre
mkdir -p $RELROOT/$DEFREL/samples/ide/os2
mkdir -p $RELROOT/$DEFREL/samples/ide/win
mkdir -p $RELROOT/$DEFREL/samples/ide/win32
mkdir -p $RELROOT/$DEFREL/samples/ide/win386
mkdir -p $RELROOT/$DEFREL/samples/ide/fortran
mkdir -p $RELROOT/$DEFREL/samples/ide/fortran/os2
mkdir -p $RELROOT/$DEFREL/samples/ide/fortran/win
mkdir -p $RELROOT/$DEFREL/samples/ide/fortran/win32
mkdir -p $RELROOT/$DEFREL/samples/ide/fortran/win386
mkdir -p $RELROOT/$DEFREL/samples/os2/dll
mkdir -p $RELROOT/$DEFREL/samples/win/alarm
mkdir -p $RELROOT/$DEFREL/samples/win/datactl
mkdir -p $RELROOT/$DEFREL/samples/win/edit
mkdir -p $RELROOT/$DEFREL/samples/win/generic
mkdir -p $RELROOT/$DEFREL/samples/win/helpex
mkdir -p $RELROOT/$DEFREL/samples/win/iconview
mkdir -p $RELROOT/$DEFREL/samples/win/life
mkdir -p $RELROOT/$DEFREL/samples/win/shootgal
mkdir -p $RELROOT/$DEFREL/samples/win/watzee
mkdir -p $RELROOT/$DEFREL/samples/win/generic/win16
mkdir -p $RELROOT/$DEFREL/samples/win/generic/win32
mkdir -p $RELROOT/$DEFREL/samples/win/generic/win386
mkdir -p $RELROOT/$DEFREL/samples/win/helpex/win16
mkdir -p $RELROOT/$DEFREL/samples/win/helpex/win32
mkdir -p $RELROOT/$DEFREL/samples/win/helpex/win386
mkdir -p $RELROOT/$DEFREL/samples/win/iconview/win16
mkdir -p $RELROOT/$DEFREL/samples/win/iconview/win32
mkdir -p $RELROOT/$DEFREL/samples/win/iconview/win386
mkdir -p $RELROOT/$DEFREL/samples/win/life/win16
mkdir -p $RELROOT/$DEFREL/samples/win/life/win32
mkdir -p $RELROOT/$DEFREL/samples/win/life/win386
mkdir -p $RELROOT/$DEFREL/samples/win/shootgal/win16
mkdir -p $RELROOT/$DEFREL/samples/win/shootgal/win32
mkdir -p $RELROOT/$DEFREL/samples/win/shootgal/win386
mkdir -p $RELROOT/$DEFREL/samples/win/watzee/win16
mkdir -p $RELROOT/$DEFREL/samples/win/watzee/win32
mkdir -p $RELROOT/$DEFREL/samples/win/watzee/win386
mkdir -p $RELROOT/$DEFREL/samples/fortran
mkdir -p $RELROOT/$DEFREL/samples/fortran/os2
mkdir -p $RELROOT/$DEFREL/samples/fortran/os2/dll
mkdir -p $RELROOT/$DEFREL/samples/fortran/os2/rexx
mkdir -p $RELROOT/$DEFREL/samples/fortran/win32
mkdir -p $RELROOT/$DEFREL/samples/fortran/win
mkdir -p $RELROOT/$DEFREL/samples/win/alarm/win16
mkdir -p $RELROOT/$DEFREL/samples/win/alarm/win32
mkdir -p $RELROOT/$DEFREL/samples/win/alarm/win386
mkdir -p $RELROOT/$DEFREL/samples/win/datactl/win386
mkdir -p $RELROOT/$DEFREL/samples/fortran/win32/dll
mkdir -p $RELROOT/$DEFREL/samples/fortran/win/dll
mkdir -p $RELROOT/$DEFREL/samples/win/datactl/win16
mkdir -p $RELROOT/$DEFREL/samples/win/datactl/win32
mkdir -p $RELROOT/$DEFREL/samples/win/edit/win16
mkdir -p $RELROOT/$DEFREL/samples/win/edit/win32
mkdir -p $RELROOT/$DEFREL/samples/win/edit/win386
mkdir -p $RELROOT/$DEFREL/src/cpplib
mkdir -p $RELROOT/$DEFREL/src/editdll
mkdir -p $RELROOT/$DEFREL/src/editdll/nt
mkdir -p $RELROOT/$DEFREL/src/editdll/nt/cw
mkdir -p $RELROOT/$DEFREL/src/editdll/nt/viw
mkdir -p $RELROOT/$DEFREL/src/editdll/os2
mkdir -p $RELROOT/$DEFREL/src/editdll/win
mkdir -p $RELROOT/$DEFREL/src/editdll/win/cw
mkdir -p $RELROOT/$DEFREL/src/editdll/win/viw
mkdir -p $RELROOT/$DEFREL/src/inc
mkdir -p $RELROOT/$DEFREL/src/os2
mkdir -p $RELROOT/$DEFREL/src/startup
mkdir -p $RELROOT/$DEFREL/src/cpplib/contain
mkdir -p $RELROOT/$DEFREL/src/os2/pdd
mkdir -p $RELROOT/$DEFREL/src/startup/386
mkdir -p $RELROOT/$DEFREL/src/startup/dos
mkdir -p $RELROOT/$DEFREL/src/startup/os2
mkdir -p $RELROOT/$DEFREL/src/startup/win
mkdir -p $RELROOT/$DEFREL/src/fortran
mkdir -p $RELROOT/$DEFREL/src/fortran/dos
mkdir -p $RELROOT/$DEFREL/src/fortran/win
mkdir -p $RELROOT/$DEFREL/src/fortran/os2
