#pmake: all build os_dos cpu_386
#
# WATCOM Presentation Graphics (PGCHART.LIB)
#

libname =       chart3r
model =         -ms -3r
module =        $[&r
cdecl =
fard =
_386 =          386

!include ../pgchart.mif
