#pmake: all build os_win cpu_386

host_OS         = win
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flib7s
model           = s
fp_model        = i87
is_stack        =

!include ../master.mif
