:set symbol="headtext$" value=" ".
:LAYOUT.
:TOC
        toc_levels=6
:TOCH5
        indent = 0
:BANNER
        left_adjust=0
        right_adjust=0
        depth=3
        place=topodd
        docsect=body
:BANREGION
        indent=0
        hoffset=right
        width=extend
        voffset=0
        depth=1
        font=4
        refnum=1
        region_position=right
        pouring=last
        contents="&amp.headtext$."
:eBANREGION
:BANREGION
        indent=0
        hoffset=left
        width='6.5i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=left
        pouring=none
        contents=rule
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=3
        place=topeven
        docsect=body
:BANREGION
        indent=0
        hoffset=left
        width=extend
        voffset=0
        depth=1
        font=4
        refnum=1
        region_position=left
        pouring=last
        contents="&amp.headtext$."
:eBANREGION
:BANREGION
        indent=0
        hoffset=left
        width='6.5i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=left
        pouring=none
        contents=rule
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=botodd
        docsect=head1
:BANREGION
        indent=0
        hoffset=left
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=headtext1
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=last
        contents=pgnuma
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=botodd
        docsect=body
:BANREGION
        indent=0
        hoffset=left
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=headtext1
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=last
        contents=pgnuma
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=boteven
        docsect=body
:BANREGION
        indent=0
        hoffset=left
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=pgnuma
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=none
        contents="Chapter &amp.$hnum1."
:eBANREGION
:eBANNER

:BANNER
        depth=3
        place=topodd
        docsect=appendix
:BANREGION
        depth=1
        refnum=1
        contents=none
:eBANREGION
:eBANNER
:BANNER
        depth=3
        place=topeven
        docsect=appendix
:BANREGION
        depth=1
        refnum=1
        contents=none
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=botodd
        docsect=appendix
:BANREGION
        indent=0
        hoffset=left
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=headtext1
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=last
        contents=pgnuma
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=boteven
        docsect=appendix
:BANREGION
        indent=0
        hoffset=left
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=pgnuma
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=none
        contents=headtext1
:eBANREGION
:eBANNER

:BANNER
        depth=3
        place=topodd
        docsect=index
:eBANNER
:BANNER
        depth=3
        place=topeven
        docsect=index
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=botodd
        docsect=index
:BANREGION
        indent=0
        hoffset=left
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents="Index"
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=last
        contents=pgnuma
:eBANREGION
:eBANNER
:BANNER
        left_adjust=0
        right_adjust=0
        depth=2
        place=boteven
        docsect=index
:BANREGION
        indent=0
        hoffset=left
        width='.7i'
        voffset=1
        depth=1
        font=0
        refnum=1
        region_position=left
        pouring=last
        contents=pgnuma
:eBANREGION
:BANREGION
        indent=0
        hoffset=right
        width=extend
        voffset=1
        depth=1
        font=0
        refnum=2
        region_position=right
        pouring=none
        contents="Index"
:eBANREGION
:eBANNER
:CONVERT.BOOKLAY.LAY
:eLAYOUT.
