#pmake: all build huge cpu_i86 os_osi
processor  = i86
system     = generic
model      = h
linkage    = static
subdir     = bchd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
