#pmake: os_qnx cpu_386 flat
#
# contmt3s.lib -- stack based multi-thread 32-bit CONTAINER library
#
host_cpu = 386

target_system = qnx
suffix = mt3s
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib$(suffix).mif
!include $(plusplus_dir)/mklib.mif
