#pmake: no_build small register 32bit inline winnt iX86 rtdll os_nt cpu_386
component=wrtlib
processor=387
model=ms
subdir=ms_r
system=winnt
convention=register
!include $(rtdll)/master.mif
!include ../objs.mif
!include $(rtdll)/mkdll.mif
