#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# iost3s.lib -- stack based 32-bit IOSTREAM library
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
