#pmake: all build compact cpu_i86 os_osi
processor  = i86
system     = generic
model      = c
linkage    = static
subdir     = scbd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
