#pmake: build compact cpu_i86 os_osi
processor  = 086
system     = generic
model      = mc
linkage    = static
subdir     = mc
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
