#pmake/25:all build small register 32bit winnt iX86 rtdll os_nt cpu_386 profile
component=clib
processor=386
model=ms
subdir=ms_rp
system=winnt
convention=register
profile=1
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
