#pmake: build os_os2 cpu_386

host_os  = os2
host_cpu = 386

srcdir = lib386

all: os2386.lib rexx.lib tcpip32.lib ftpapi.lib opengl.lib glut.lib &
     libtk.lib libaux.lib mmpm2.lib rtmidi.lib upm32.lib libuls.lib &
     libconv.lib

!include ../master.mif
