#pmake/50: build2 small register 32bit inline winnt iX86 rtdll os_nt cpu_386 profile
component=mathlib
processor=387
model=ms
subdir=ms_rp
system=winnt
convention=register
profile=1
!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
