#pmake: build os_dos cpu_386 386 intel necdos
#
# Open Watcom Debugger makefile for dsx (NEC)
#

host_os  = dos
host_cpu = 386

machine  = nec

syshdir = ../h;../../dos/h

sysobjs =   &
    dsxfork.obj &
    dsxstart.obj &
    dsxchk.obj &
    dsxcmd.obj &
    dsxfilio.obj &
    necscrn.obj &
    dsxlkup.obj &
    dsxhdlr.obj &
    dsxmem.obj


!include ../../master.mif
