#pmake: no_build1 flat stack 32bit inline os2 iX86 rtdll os_os2 cpu_386
component=wrtlib
processor=387
model=mf
subdir=mf_s
system=os2
convention=stack
!include $(rtdll)/master.mif
!include ../objs.mif
!include $(rtdll)/mkdll.mif
