#pmake: build flat cpu_386 os_os2 dynamic debug

host_cpu       = 386
suffix         = mt3r
subdir         = os23rmtd.dll
linkage        = dynamic
release_cpplib = 0

define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
