#pmake: all build small cpu_i86 os_win
#
# cplxs.lib -- small memory-model COMPLEX library fpc for Windows
#
processor  = i86
system     = windows
model      = s
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
