#pmake: all build os_nt cpu_386

host_OS         = nt
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flib7
model           = f
fp_model        = i87
is_MT           =
is_DLL          =

!include ..\master.mif
