#pmake: build large cpu_i86 os_win
#
# strgl.lib -- large memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
