#pmake: build large cpu_i86 os_osi
processor  = 086
system     = generic
model      = ml
linkage    = static
subdir     = ml
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
