#pmake: all build large cpu_i86 os_osi
processor  = i86
system     = generic
model      = l
linkage    = static
subdir     = bcbd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
