#pmake: build medium cpu_i86 os_osi
processor  = 086
system     = generic
model      = mm
linkage    = static
subdir     = mm
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
