#pmake: all build os_os2 cpu_386

host_OS         = os2
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flib7s
model           = f
fp_model        = i87
is_MT           =
is_DLL          =
is_stack        =

!include ..\master.mif
