fp_model        = c
exe             = wf386
form            = dos4g
__386__         =
!ifdef __UNIX__
share_objs      = ../obj386/
!else
share_objs      = ..\obj386\
!endif
japan_objs      =

!include        ../makego.mif
