#pmake: all build small cpu_i86 os_win
#
# iosts.lib -- small memory-model IOSTREAM library for Windows
#
processor  = i86
system     = windows
model      = s
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
