# makefile for GRAPHS.LIB

libname =       graphs
model =         -ms -d_SUPERVGA
module =        $[&
cdecl =         _loadds
fard =
_386 =
_qnx =
asm_cmd =       wasm
asm_flags =     -ms -i..\inc -d_MODEL=_SMALL

!include ..\graphics.mif
