#pmake: build os_dos cpu_386
# makefile for GRAPHS.LIB

libname =       graphs
model =         -ms -d_SUPERVGA
module =        $[&
cdecl =         _loadds
fard =
_386 =
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -ms -i..\inc -d_MODEL=_SMALL

!include $(graphics_prefix)../graphics.mif
