#pmake: all build serv remote os_win cpu_i86 cpu_386 nov x86
host_cpu = i86

gui = 1
os = win
srv = nov
cpu = x86

extra_objs = $(remote_objs) novdos.obj
extra_flags_novdos = -zu

!include $(trap_dir)/serv.mif
