#pmake: all build os_os2 cpu_386
#
# WATCOM Presentation Graphics (PGCHART.LIB)
#

host_CPU = 386
host_OS = os2

libname =       charto
model =         -3r -mf -bt=OS2
module =        $[&
cdecl =
fard =
_386 =          386

!include ../pgchart.mif
