#pmake: build trap remote os_nt cpu_i86 cpu_386 vdm x86
host_CPU = 386
host_OS = nt

os = nt
srv = vdm
cpu = x86
which = TRAP

extra_objs = $(remote_objs) vdmclint.obj

!include $(trap_dir)/master.mif
