#pmake: all build flat cpu_386 os_osi
#
# iostmt3r.lib -- register based multi-thread 32-bit IOSTREAM library
#
host_cpu = 386

suffix = mt3r
target_system = generic
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
define_target_include = $(plusplus_dir)/lib$(suffix).mif
!include $(plusplus_dir)/mklib.mif
