pick( MSG_DISK_ERROR,		"Disk error during %s: %Z" ,
				"%s: %Zの間にディスクエラーが生じました" )
pick( MSG_PREMATURE_EOF,	"Premature end of file encountered" ,
				"途中でEOFが検出されました" )
pick( MSG_NO_LRO_PHARLAP,
                                "No loader resolved fixups allowed in EASY OMF" ,
                                "EASY OMFではローダで解決するフィックスアップは許されていません" )
pick( MSG_MAX_REC_EXCEEDED,	"Maximum object record size (%u byte) exceeded" ,
                                "オブジェクト・レコードの最大サイズ(%u ﾊﾞｲﾄ)を越えています" )
pick( MSG_MS386_NO_4KPAGE,
                                "No 4k Page-aligned segments in MS386 OMF" ,
                                "MS386 OMFには4Kページ整列セグメントがありません" )
pick( MSG_MS386_NO_ACCESS,
                                "Access classes (RW, EO, RO, ER) not supported in MS386 OMF" ,
                                "MS386 OMFではアクセスクラス(RW,EO,RO,ER)はサポートされていません" )
