#pmake: build compact cpu_i86 os_osi
#
# plibc -- 16-bit compact memory-model PLIB
#
processor  = 086
system     = generic
model      = mc
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
