#pmake: build huge cpu_i86 os_osi
#
# cplxh.lib -- huge memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mh
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
