#pmake: all os_dos cpu_i86

host_OS         = dos
host_CPU        = i86

# FORTRAN project definitions
use_ems         =

# code generator project definitions
target_CPU      = 386

!include ..\master.mif
