#pmake: all build trap remote os_os2 cpu_i86 cpu_386 par x86
host_cpu = 386

os = os2v2
srv = par
cpu = x86

extra_objs = $(remote_objs) paros22.obj

!include $(trap_dir)\trap.mif
!include ..\os2v2.mif
