#pmake: build flat cpu_386 os_osi
#
# cplx7r.lib -- register based 32-bit COMPLEX library -fpi
#
processor  = 387
system     = generic
model      = mf
convention = register
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
