#pmake: build os_nt cpu_386

host_OS             = nt

proj_name          = directx
include_dir        = ../../include/directx
root_include_dir   = ../../include
lib_dir            = ../../lib/directx
what_to_build      = headers

!include ../../master.mif
