#pmake: build compact cpu_i86 os_win
processor  = 086
system     = windows
model      = mc
linkage    = static
subdir     = mc
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
