#pmake: debug flat cpu_386 os_os2
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
subdir     = mf_rd

release_cpplib = 0

define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
