#pmake: all build large cpu_i86 os_os2
#
# contmt.lib -- large memory-model OS/2 multi-thread CONTAINER library
#
processor  = i86
system     = os2
model      = l
convention =
linkage    = static
mthreaded  = 1
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
