#pmake: no_build1 flat stack 32bit inline winnt iX86 rtdll os_nt cpu_386
component=wrtlib
processor=387
model=mf
subdir=mf_s
system=winnt
convention=stack
!include $(rtdll)/master.mif
!include ../objs.mif
!include $(rtdll)/mkdll.mif
