#pmake: build os_win cpu_i86
#
# Open Watcom Debugger makefile for Windows
#

host_OS=win
host_CPU=i86
display=gui

sysobjs =   &
    wininit.obj &
    winchk.obj &
    wincmd.obj &
    winfilio.obj &
    winlkup.obj &
    wguiscrn.obj

!include ../../master.mif
