#pmake: all build flat cpu_386 os_osi os_dos os_linux
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
host_cpu = 386

suffix = 3r
target_system = generic
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
define_target_include = $(plusplus_dir)/lib32$(suffix).mif
!include $(plusplus_dir)/mklib.mif
