#pmake: all os_dos cpu_i86

host_OS         = dos
host_CPU        = i86

# FORTRAN project definitions
lib_name        = flibl
model           = l
fp_model        = c
is_NEC          =

!include ../master.mif
