/****************************************************************************
*
*                            Open Watcom Project
*
*    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
*
*  ========================================================================
*
*    This file contains Original Code and/or Modifications of Original
*    Code as defined in and that are subject to the Sybase Open Watcom
*    Public License version 1.0 (the 'License'). You may not use this file
*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
*    provided with the Original Code and Modifications, and is also
*    available at www.sybase.com/developer/opensource.
*
*    The Original Code and all software distributed under the License are
*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
*    NON-INFRINGEMENT. Please see the License for the specific language
*    governing rights and limitations under the License.
*
*  ========================================================================
*
* Description:  WHEN YOU FIGURE OUT WHAT THIS FILE DOES, PLEASE
*               DESCRIBE IT HERE!
*
****************************************************************************/


//
// constants indicating function's index in tables
//

enum {
    IF_ABS,
    IF_ACOS,
    IF_AIMAG,
    IF_AINT,
    IF_ALGAMA,
    IF_ALLOCATED,
    IF_ALOG,
    IF_ALOG10,
    IF_AMAX0,
    IF_AMAX1,
    IF_AMIN0,
    IF_AMIN1,
    IF_AMOD,
    IF_ANINT,
    IF_ASIN,
    IF_ATAN,
    IF_ATAN2,
    IF_BTEST,
    IF_CABS,
    IF_CCOS,
    IF_CDABS,
    IF_CDCOS,
    IF_CDEXP,
    IF_CDLOG,
    IF_CDSIN,
    IF_CDSQRT,
    IF_CEXP,
    IF_CHAR,
    IF_CLOG,
    IF_CMPLX,
    IF_CONJG,
    IF_COS,
    IF_COSH,
    IF_COTAN,
    IF_CQABS,
    IF_CQCOS,
    IF_CQEXP,
    IF_CQLOG,
    IF_CQSIN,
    IF_CQSQRT,
    IF_CSIN,
    IF_CSQRT,
    IF_DABS,
    IF_DACOS,
    IF_DASIN,
    IF_DATAN,
    IF_DATAN2,
    IF_DBLE,
    IF_DCMPLX,
    IF_DCONJG,
    IF_DCOS,
    IF_DCOSH,
    IF_DCOTAN,
    IF_DDIM,
    IF_DERF,
    IF_DERFC,
    IF_DEXP,
    IF_DFLOAT,
    IF_DGAMMA,
    IF_DIM,
    IF_DIMAG,
    IF_DINT,
    IF_DLGAMA,
    IF_DLOG,
    IF_DLOG10,
    IF_DMAX1,
    IF_DMIN1,
    IF_DMOD,
    IF_DNINT,
    IF_DPROD,
    IF_DREAL,
    IF_DSIGN,
    IF_DSIN,
    IF_DSINH,
    IF_DSQRT,
    IF_DTAN,
    IF_DTANH,
    IF_ERF,
    IF_ERFC,
    IF_EXP,
    IF_FLOAT,
    IF_GAMMA,
    IF_HFIX,
    IF_I1ABS,
    IF_I1AND,
    IF_I1BCHNG,
    IF_I1BCLR,
    IF_I1BSET,
    IF_I1BTEST,
    IF_I1DIM,
    IF_I1EOR,
    IF_I1LSHIFT,
    IF_I1MAX0,
    IF_I1MIN0,
    IF_I1MOD,
    IF_I1NOT,
    IF_I1OR,
    IF_I1RSHIFT,
    IF_I1SHA,
    IF_I1SHC,
    IF_I1SHFT,
    IF_I1SHL,
    IF_I1SIGN,
    IF_I2ABS,
    IF_I2AND,
    IF_I2BCHNG,
    IF_I2BCLR,
    IF_I2BSET,
    IF_I2BTEST,
    IF_I2DIM,
    IF_I2EOR,
    IF_I2LSHIFT,
    IF_I2MAX0,
    IF_I2MIN0,
    IF_I2MOD,
    IF_I2NOT,
    IF_I2OR,
    IF_I2RSHIFT,
    IF_I2SHA,
    IF_I2SHC,
    IF_I2SHFT,
    IF_I2SHL,
    IF_I2SIGN,
    IF_IABS,
    IF_IAND,
    IF_IBCHNG,
    IF_IBCLR,
    IF_IBSET,
    IF_ICHAR,
    IF_IDIM,
    IF_IDINT,
    IF_IDNINT,
    IF_IEOR,
    IF_IFIX,
    IF_IMAG,
    IF_INDEX,
    IF_INT,
    IF_IOR,
    IF_IQINT,
    IF_IQNINT,
    IF_ISHA,
    IF_ISHC,
    IF_ISHFT,
    IF_ISHL,
    IF_ISIGN,
    IF_ISIZEOF,
    IF_LEN,
    IF_LENTRIM,
    IF_LGAMMA,
    IF_LGE,
    IF_LGT,
    IF_LLE,
    IF_LLT,
    IF_LOC,
    IF_LOG,
    IF_LOG10,
    IF_LSHIFT,
    IF_MAX,
    IF_MAX0,
    IF_MAX1,
    IF_MIN,
    IF_MIN0,
    IF_MIN1,
    IF_MOD,
    IF_NINT,
    IF_NOT,
    IF_QABS,
    IF_QACOS,
    IF_QASIN,
    IF_QATAN,
    IF_QATAN2,
    IF_QCMPLX,
    IF_QCONJG,
    IF_QCOS,
    IF_QCOSH,
    IF_QCOTAN,
    IF_QDIM,
    IF_QERF,
    IF_QERFC,
    IF_QEXP,
    IF_QEXT,
    IF_QGAMMA,
    IF_QIMAG,
    IF_QINT,
    IF_QLGAMA,
    IF_QLOG,
    IF_QLOG10,
    IF_QMAX1,
    IF_QMIN1,
    IF_QMOD,
    IF_QNINT,
    IF_QPROD,
    IF_QSIGN,
    IF_QSIN,
    IF_QSINH,
    IF_QSQRT,
    IF_QTAN,
    IF_QTANH,
    IF_REAL,
    IF_RSHIFT,
    IF_SIGN,
    IF_SIN,
    IF_SINH,
    IF_SNGL,
    IF_SQRT,
    IF_TAN,
    IF_TANH,
    IF_VOLATILE,

    IF_MAX_NAME   = IF_VOLATILE
};

#define IF_MAX_LEN      6       //  length of longest i.f. name

#define IF_NO_MORE      254
#define MAGIC           255
