#pmake: all build os_dos cpu_i86
#
# WATCOM Presentation Graphics (PGCHART.LIB)
#

libname =       charts
model =         -ms
module =        $[&
cdecl =         _loadds
fard =
_386 =

!include ../pgchart.mif
