#pmake: build os_dos cpu_386
# makefile for GRAPH3S.LIB

libname =       graph3s
model =         -ms -3s -d_SUPERVGA -d__STACK
module =        $[&s
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -ms -3s -fo=$[&.obj -i..\inc -d_MODEL=_SMALL -d_386

!include ../graphics.mif
