#pmake: trap remote os_dos cpu_i86 cpu_386 tcp x86

# NOTE: This is not working at present...

os = dos
srv = tcp
cpu = x86
dos_large_model = 1

extra_objs = $(remote_objs)
extra_incs = c:\watt32\inc
extra_libs = c:\watt32\lib\wattcpwl.lib

!include $(trap_dir)\trap.mif
