#pmake: all build medium cpu_i86 os_win
#
# strgm.lib -- medium memory-model STRING library for Windows
#
processor  = i86
system     = windows
model      = m
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
