#pmake/25: build debug flat register 32bit winnt iX86 rtdll os_nt cpu_386

component  = clib
processor  = 386
model      = mf
subdir     = mf_r
system     = winnt
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
