#pmake: all build trap remote os_win cpu_i86 cpu_386 nov x86
host_cpu = i86

os = win
srv = tcp
cpu = x86

extra_objs = $(remote_objs)
extra_libs = $(watcom_dir)\lib\winsock.lib

!include $(trap_dir)\trap.mif
