#pmake: os_os2 cpu_i86
host_OS = os2
host_CPU = i86

# The following modules contain functions called from a separate thread and
# therefore must assume that SS != DS
extra_c_flags_int     = -zu
extra_c_flags_biosos2 = -zu

!include ../mif/master.mif
