#pmake: all build compact cpu_i86 os_osi
#
# plibc -- 16-bit compact memory-model PLIB
#
processor  = i86
system     = generic
model      = c
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
