#pmake: all build large cpu_i86 os_os2
#
# plibmtl -- 16-bit large memory-model PLIB multi-thread OS/2
#
processor  = i86
system     = os2
model      = l
convention =
linkage    = static
mthreaded  = 1
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
