#pmake: build flat cpu_386 os_os2
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
fs_registration = yes
define_library_include = $(cpplib_dir)/iostream/iostream.mif
define_deps_include = $(cpplib_dir)/iostream/deps.mif
!include $(cpplib_dir)/mklib.mif
