#pmake: all build compact cpu_i86 os_osi
#
# contc.lib -- compact memory-model CONTAINER library
#
processor  = i86
system     = generic
model      = c
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
