#pmake: build compact cpu_i86 os_osi
#
# contc.lib -- compact memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = mc
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(cpplib_dir)/mklib.mif
