#pmake: all build serv remote os_win cpu_i86 cpu_386 tcp x86
host_cpu = i86

gui = 1
os = win
srv = tcp
cpu = x86

extra_objs = $(remote_objs)
extra_libs = $(watcom_dir)/lib/winsock.lib

!include $(trap_dir)/serv.mif
