#pmake: all build serv remote os_nt cpu_i86 cpu_386 tcp x86

gui = 1
os = win
srv = tcp
cpu = x86

extra_objs = $(remote_objs)
extra_libs = $(watcom_dir)\lib\winsock.lib

!include $(trap_dir)\serv.mif
