#pmake: nomodel cpu_axp os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
host_cpu = axp

pd_registration = yes
suffix = mt
target_system = ntaxp
text = -hd
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/libaxp$(suffix).mif
!include $(plusplus_dir)/mklib.mif
