#pmake: all build medium cpu_i86 os_osi
#
# contm.lib -- medium memory-model CONTAINER library
#
processor  = i86
system     = generic
model      = m
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
