#pmake: build os_os2 cpu_386
#
# Open Watcom Debugger makefile for OS/2
#

host_OS  = os2
host_CPU = 386

syshdir  =

sysobjs =            &
        os22ini.obj  &
        os2chk.obj   &
        os2cmd.obj   &
        os22flio.obj &
        os2scrn.obj

!include ../../master.mif
