#pmake: all os_dos cpu_i86

host_OS         = dos
host_CPU        = i86

# FORTRAN project definitions
lib_name        = flib7l
model           = l
fp_model        = i
is_NEC          =

!include ..\master.mif
