#pmake: os_dos cpu_i86 i86 intel
#
# WATCOM Debugger makefile for NEC
#

host_OS=dos
host_CPU=i86
display=char

machine = nec

sysobjs =   &
    fork.obj &
    dosstl.obj &
    doschk.obj &
    doscmd.obj &
    dosfilio.obj &
    doslkup.obj &
    dosmem.obj &
    dosgrow.obj &
    dosalloc.obj &
    dostrap.obj &
    necscrn.obj

!include ../../master.mif
