#pmake: all build compact cpu_i86 os_win
#
# iostc.lib -- compact memory-model IOSTREAM library for Windows
#
processor  = i86
system     = windows
model      = c
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
