VERSION = _WINNT
model = 
host_CPU = axp		# only defined for axp (for now)
host_OS	 = nt
cpu = alpha

!include cproj.mif
!include defrule.mif

!include wres.mif

guilib  = $(guidir)\win\guintaxp$(model).lib
guihdir = $(guidir)\h

!include ../setup.mif
