#pmake/25: build2 small register 32bit winnt iX86 rtdll os_nt cpu_386
component=clib
processor=386
model=ms
subdir=ms_r
system=winnt
convention=register
!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
