objs = &
b.obj &
diag01.obj &
diag02.obj &
diag03.obj &
diag04.obj &
diag05.obj &
diag06.obj &
diag07.obj
error.obj &
include.obj &
irp.obj &

asm_flags_diag01 = -4s
asm_flags_diag02 = -3
asm_flags_diag03 = -wx
asm_flags_diag05 = -e100

!include ../test.mif
