#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp IOSTREAM library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
