#pmake/50: build debug flat register 32bit inline winnt iX86 rtdll os_nt cpu_386

component  = mathlib
processor  = 387
model      = mf
subdir     = mf_rd
system     = winnt
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
