#pmake: all build medium cpu_i86 os_osi
#
# iostm.lib -- medium memory-model IOSTREAM library
#
processor  = i86
system     = generic
model      = m
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
