#pmake: all build compact cpu_i86 os_win
#
# cplxc.lib -- compact memory-model COMPLEX library fpc for Windows
#
processor  = i86
system     = windows
model      = c
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
