#pmake: serv remote os_nt cpu_386 nov axp
host_CPU = axp

gui = 1
os = nt
srv = nov
cpu = axp

extra_objs = $(remote_objs) novnt.obj
extra_libs = $(lang_root)/libaxp/nt/wsock32.lib

!include $(trap_dir)/serv.mif
