#pmake: build os_os2 cpu_386
#
# Open Watcom Debugger makefile for OS/2 PM
#

host_OS  = os2
host_CPU = 386
display  = gui

sys_windowed = 1

syshdir  =

sysobjs =            &
        os22ini.obj  &
        os2chk.obj   &
        os2cmd.obj   &
        os22flio.obj &
        pmscrn2.obj

!include ../../master.mif
