fp_model        = c
lib             = wflib
__386__         =
form            = pharlap       # for ifbuild
oshdrs          = $(watcomdir)os220_h
__mt__          =
# share_objs    = ..\386\

!include        ..\makert.mif
