#pmake: build large cpu_i86 os_osi
#
# iostl.lib -- large memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
