#pmake: all build large cpu_i86 os_osi
#
# iostl.lib -- large memory-model IOSTREAM library
#
processor  = i86
system     = generic
model      = l
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
