#pmake: nomodel cpu_axp os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
mthreaded    = 1
pd_registration = yes
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
