#pmake: all build large cpu_i86 os_win
#
# plibl -- 16-bit large memory-model PLIB for Windows
#
processor  = i86
system     = windows
model      = l
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
