#pmake: debug flat cpu_386 os_os2
#
# cont3r.lib -- register based 32-bit CONTAINER library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
release_cpplib  = 0
fs_registration = yes
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
