#pmake: all build medium cpu_i86 os_win
#
# contm.lib -- medium memory-model CONTAINER library for Windows
#
host_cpu = i86

suffix = m
target_system = windows
text = -zW
define_library_include = $(plusplus_contain_dir)/contain.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
