#pmake: all build medium cpu_i86 os_win
#
# contm.lib -- medium memory-model CONTAINER library for Windows
#
processor  = i86
system     = windows
model      = m
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
