fp_model        = i87
lib             = wflib7
__386__         =
form            = pharlap       # this is for ifbuild
oshdrs          = $(watcomdir)os220_h
__mt__          =
# share_objs    = ..\387\

!include        ..\makert.mif
