#pmake: all build large cpu_i86 os_osi
#
# plibl -- 16-bit large memory-model PLIB
#
host_cpu = i86

suffix = l
target_system = generic
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
