#pmake: build os_dos cpu_i86
# makefile for GRAPHS.LIB

libname =       graphs
model =         -ms -d_NEC_PC
module =        $[&
cdecl =         _loadds
fard =
_386 =
_qnx =
asm_cmd =       wasm
asm_flags =     -zq -q -ms -i..\inc -d_MODEL=_SMALL -d_NEC_PC
_NEC_PC =       1

!include ../graphics.mif
