#pmake: no_build1 flat register 32bit calls os2 iX86 rtdll os_os2 cpu_386
component=wrtlib
processor=386
model=mf
subdir=mf_r
system=os2
convention=register
!include $(rtdll)/master.mif
!include ../objs.mif
!include $(rtdll)/mkdll.mif
