#pmake: build small cpu_i86 os_win
#
# strgs.lib -- small memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
