#pmake: build small cpu_386 os_nov
#
# cplx73s.lib -- Netware stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = netware
model      = ms
convention = stack
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
