#pmake: build os_nt cpu_386

host_os       = nt
host_cpu      = 386

proj_name     = directx
root_dir      = ../..
include_dir   = $(root_dir)/include/directx
lib_dir       = $(root_dir)/lib/directx
what_to_build = libs

!include ../../master.mif
