#pmake: build compact cpu_i86 os_osi
#
# iostc.lib -- compact memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
