#pmake: all build compact cpu_i86 os_osi
#
# iostc.lib -- compact memory-model IOSTREAM library
#
processor  = i86
system     = generic
model      = c
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
