#pmake/50: build2 small stack 32bit calls os2 iX86 rtdll os_os2 cpu_386
component=mathlib
processor=386
model=ms
subdir=ms_s
system=os2
convention=stack
!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
