#pmake: build small cpu_i86 os_osi
#
# plibs -- 16-bit small memory-model PLIB
#
processor  = 086
system     = generic
model      = ms
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(cpplib_dir)/mklib.mif
