#pmake: all build os_dos cpu_386

host_OS         = dos
host_CPU        = 386

# FORTRAN project definitions
lib_name        = flibs
model           = s
fp_model        = c
is_stack        =

!include ..\master.mif
