#pmake: all build small cpu_i86 os_osi
processor  = i86
system     = generic
model      = s
linkage    = static
subdir     = scsd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
