#pmake: all build medium cpu_i86 os_osi
#
# strgm.lib -- medium memory-model STRING library
#
host_cpu = i86

suffix = m
target_system = generic
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
