#pmake/50: build debug flat register 32bit calls os2 iX86 rtdll os_os2 cpu_386

component  = mathlib
processor  = 386
model      = mf
subdir     = mf_rd
system     = os2
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
