#pmake: build small cpu_i86 os_osi
#
# cplxs.lib -- small memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = ms
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
