#pmake: all build large cpu_i86 os_os2
#
# plibmtl -- 16-bit large memory-model PLIB multi-thread OS/2
#
host_cpu = i86

suffix = mtl
target_system = os2
define_library_include = $(plusplus_runtime_dir)/plib.mif
define_target_include = $(plusplus_dir)/lib16$(suffix).mif
!include $(plusplus_dir)/mklib.mif
