#pmake/50: build small register 32bit inline winnt iX86 rtdll os_nt cpu_386

component  = mathlib
processor  = 387
model      = ms
subdir     = ms_r
system     = winnt
convention = register
debug      = 1

!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
