#pmake: all build huge cpu_i86 os_osi
#
# conth.lib -- huge memory-model CONTAINER library
#
processor  = i86
system     = generic
model      = h
linkage    = static
define_library_include = $(plusplus_contain_dir)/contain.mif
!include $(plusplus_dir)/mklib.mif
