pick( ERR_DUMMY,                "Dummy msg",
                                "Dummy msg" )
pick( ERR_INTERN,               "Internal Error",
                                "Internal Error" )
pick( ERR_STR_NOT_FOUND,        "Resourcestring not found",
                                "Resourcestring not found" )
pick( ERR_FILE_IO,              "FileIO %s %s",
                                "FileIO %s %s" )
pick( ERR_NO_MEMORY,            "Out of memory!",
                                "Out of memory!" )
pick( ERR_NO_HANDLES,           "Out of file handles!",
                                "Out of file handles!" )
pick( ERR_LOGIC_MAC,            "Logic error: get_macroline for file",
                                "Logic error: get_macroline for file" )
pick( ERR_INF_REOPEN,           "Calling reopen_inc_fp",
                                "Calling reopen_inc_fp" )
pick( ERR_INF_LINE_FILE,        "\tIncluded from line %s of file '%s'",
                                "\tIncluded from line %s of file '%s'" )
pick( ERR_INF_TAG,              "\tCalled from GML tag '%s' in",
                                "\tCalled from GML tag '%s' in" )
pick( ERR_INF_MAC_DEF,          "\tLine %s of macro '%s' defined at line %d of file '%s'",
                                "\tLine %s of macro '%s' defined at line %d of file '%s'" )
pick( ERR_INC_UNKNOWN,          "\tERR Included from unknown ( master document? )",
                                "\tERR Included from unknown ( master document? )" )
pick( WNG_FILEATTR_IGNORED,     "File attribute ignored (%s) %s",
                                "File attribute ignored (%s) %s" )
pick( ERR_MAX_INPUT_NESTING,    "Max input nesting exceeded %s",
                                "Max input nesting exceeded %s" )
pick( ERR_INPUT_FILE_NOT_FOUND, "Input file not found %s",
                                "Input file not found %s" )
pick( INF_CURR_INPUT,           "Current %s is '%s'",
                                "Current %s is '%s'" )
pick( INF_CURR_LINE,            "Current file is '%s'(%s)",
                                "Current file is '%s'(%s)" )
pick( ERR_GOTO,                 "Goto label not found %s Line %d of macro '%s'",
                                "Goto label not found %s Line %d of macro '%s'" )
pick( ERR_MISSING_MAINFILENAME, "Missing main file name",
                                "Missing main file name" )
pick( ERR_IF_LEVEL,             "If nesting level bot zero at EOF %s",
                                "If nesting level bot zero at EOF %s" )
pick( INF_INDENT_REM,           "%s<< Indentremoved",
                                "%s<< Indentremoved" )
pick( INF_INCLUDED,             "\tIncluded from %s",
                                "\tIncluded from %s" )
pick( INF_STAT_1,               "Statistics:",
                                "Statistics:" )
pick( INF_STAT_2,               "Max inc level: %6s",
                                "Max inc level: %6s" )
pick( INF_STAT_3,               "  Error count: %6s",
                                "  Error count: %6s" )
pick( INF_STAT_4,               "Warning count: %6s",
                                "Warning count: %6s" )
pick( INF_STAT_5,               "   Returncode: %6s",
                                "   Returncode: %6s" )
pick( INF_CMDLINE,              "cmdline=%s",
                                "cmdline=%s" )
pick( INF_PASS_1,               "Starting pass %s of %s ( %s mode )",
                                "Starting pass %s of %s ( %s mode )" )
pick( INF_PASS_2,               "  End of pass %d of %d ( %s mode )",
                                "  End of pass %d of %d ( %s mode )" )
pick( WNG_IGN_OPTION,           "Option ignored: %s",
                                "Option ignored: %s" )
pick( ERR_PU_NUM,               "Workfile number not 1 - 9 Line %s of %s '%s'",
                                "Workfile number not 1 - 9 Line %s of %s '%s'" )
pick( ERR_SUBSCRIPT_OUT_OF_RANGE, "Subscript out of range (-1000000 - +1000000) %s",
                                "Subscript out of range (-1000000 - +1000000) %s" )
pick( ERR_LOGIC_ERR,            "Logic error in %s",
                                "Logic error in %s"  )

