pick( ERR_DUMMY,       "Dummy msg",    // do not delete
                       "Dummy msg" )

pick( INF_USE_01,      " ", " " )

pick( INF_USE_02,      "Usage: wgml [options] srcfile [options]",
                       "Usage: wgml [options] srcfile [options]" )

pick( INF_USE_03,      "Options:",
                       "Options:" )

pick( INF_USE_04,      "-q\t\tQuiet, don't show product info.",
                       "-q\t\tQuiet, don't show product info." )

pick( INF_USE_05,      "-r\t\tResearch, no formatting, only process some GML/SCR keywords,",
                       "-r\t\tResearch, no formatting, only process some GML/SCR keywords," )

pick( INF_USE_06,      "\t\tfollow .im, .ap, :INCLUDE tags and show substituted lines.",
                       "\t\tfollow .im, .ap, :INCLUDE tags and show substituted lines." )

pick( INF_USE_07,      "\t\t> >substituted line< <",
                       "\t\t> >substituted line< <" )

pick( INF_USE_08,      "\t\t) )resulting text line after macro / tag processing( (",
                       "\t\t) )resulting text line after macro / tag processing( (" )

pick( INF_USE_END,     "\tother options to be done / documented.",
                       "\tother options to be done / documented." )

/* The last usage msg MUST have the id INF_USE_END */


