#pmake/75: small register 32bit calls winnt iX86 rtdll os_nt cpu_386 cpplib

component  = cpplib
processor  = 386
model      = ms
subdir     = ms_rd
system     = winnt
convention = register
debug      = 1

!include $(rtdll_dir)/master.mif
!include ../objs.mif
!include $(rtdll_dir)/mkdll.mif
