#pmake: all build os_nt cpu_386

targos          = nt386

!ifdef prebuild
!include $(posix_dir)/mif/bld_cmds.mif
!else
!include $(posix_dir)/mif/commands.mif
!endif

!include $(posix_dir)/mif/makeall.mif
