type = win
os = pm
build_target = os2_pm
sys=os2 pm
extra_lib=os2.lib
compiler = comp286
model=l
xflags=-zu-s
sysinclude=$(lang_root)\h\os21x;

target : sample.exe .SYMBOLIC
    @%null

!include ../makefile
