#pmake: all build trap remote os_os2 cpu_i86 cpu_386 vdm x86

os  = os2v2
srv = vdm
cpu = x86

extra_cflags = -d2
extra_objs = $(remote_objs) vdmcli2.obj
extra_libs = $(os2386)

!include $(trap_dir)\trap.mif
