call ..\setup11
call ..\mkit isv
call ..\mkit c_readme
call ..\mkit clr
call ..\mkit wprof
call ..\mkit cguide
call ..\mkit pguide
call ..\mkit lguide
call ..\mkit tools
call ..\mkit wd
call ..\mkit rescomp
call ..\mkit clib
call ..\mkit cpplib
call ..\mkit wccerrs
call ..\mkit wpperrs
call ..\mkit f_readme
call ..\mkit fuguide
call ..\mkit fpguide
call ..\mkit ftools
call ..\mkit f77graph
call ..\mkit f77lr
call ..\mkit wfcerrs
call ..\mkit cmix
call ..\mkit fmix
