/*
    OS/2 Presentation Manager error codes include file
    for 32-bit development.
*/


#ifdef INCL_WINERRORS

#ifndef INCL_WINERRORS_INCL
#define INCL_WINERRORS_INCL

#define PMERR_INVALID_HWND                  0x1001
#define PMERR_INVALID_HMQ                   0x1002
#define PMERR_PARAMETER_OUT_OF_RANGE        0x1003
#define PMERR_WINDOW_LOCK_UNDERFLOW         0x1004
#define PMERR_WINDOW_LOCK_OVERFLOW          0x1005
#define PMERR_BAD_WINDOW_LOCK_COUNT         0x1006
#define PMERR_WINDOW_NOT_LOCKED             0x1007
#define PMERR_INVALID_SELECTOR              0x1008
#define PMERR_CALL_FROM_WRONG_THREAD        0x1009
#define PMERR_RESOURCE_NOT_FOUND            0x100A
#define PMERR_INVALID_STRING_PARM           0x100B
#define PMERR_INVALID_HHEAP                 0x100C
#define PMERR_INVALID_HEAP_POINTER          0x100D
#define PMERR_INVALID_HEAP_SIZE_PARM        0x100E
#define PMERR_INVALID_HEAP_SIZE             0x100F
#define PMERR_INVALID_HEAP_SIZE_WORD        0x1010
#define PMERR_HEAP_OUT_OF_MEMORY            0x1011
#define PMERR_HEAP_MAX_SIZE_REACHED         0x1012
#define PMERR_INVALID_HATOMTBL              0x1013
#define PMERR_INVALID_ATOM                  0x1014
#define PMERR_INVALID_ATOM_NAME             0x1015
#define PMERR_INVALID_INTEGER_ATOM          0x1016
#define PMERR_ATOM_NAME_NOT_FOUND           0x1017
#define PMERR_QUEUE_TOO_LARGE               0x1018
#define PMERR_INVALID_FLAG                  0x1019
#define PMERR_INVALID_HACCEL                0x101A
#define PMERR_INVALID_HPTR                  0x101B
#define PMERR_INVALID_HENUM                 0x101C
#define PMERR_INVALID_SRC_CODEPAGE          0x101D
#define PMERR_INVALID_DST_CODEPAGE          0x101E
#define PMERR_UNKNOWN_COMPONENT_ID          0x101f
#define PMERR_UNKNOWN_ERROR_CODE            0x1020
#define PMERR_SEVERITY_LEVELS               0x1021

#define PMERR_INVALID_RESOURCE_FORMAT       0x1034

#define PMERR_NO_MSG_QUEUE                  0x1036
#define PMERR_WIN_DEBUGMSG                  0x1037
#define PMERR_QUEUE_FULL                    0x1038
#define PMERR_LIBRARY_LOAD_FAILED           0x1039
#define PMERR_PROCEDURE_LOAD_FAILED         0x103A
#define PMERR_LIBRARY_DELETE_FAILED         0x103B
#define PMERR_PROCEDURE_DELETE_FAILED       0x103C
#define PMERR_ARRAY_TOO_LARGE               0x103D
#define PMERR_ARRAY_TOO_SMALL               0x103E
#define PMERR_DATATYPE_ENTRY_BAD_INDEX      0x103F
#define PMERR_DATATYPE_ENTRY_CTL_BAD        0x1040
#define PMERR_DATATYPE_ENTRY_CTL_MISS       0x1041
#define PMERR_DATATYPE_ENTRY_INVALID        0x1042
#define PMERR_DATATYPE_ENTRY_NOT_NUM        0x1043
#define PMERR_DATATYPE_ENTRY_NOT_OFF        0x1044
#define PMERR_DATATYPE_INVALID              0x1045
#define PMERR_DATATYPE_NOT_UNIQUE           0x1046
#define PMERR_DATATYPE_TOO_LONG             0x1047
#define PMERR_DATATYPE_TOO_SMALL            0x1048
#define PMERR_DIRECTION_INVALID             0x1049
#define PMERR_INVALID_HAB                   0x104A
#define PMERR_INVALID_HSTRUCT               0x104D
#define PMERR_LENGTH_TOO_SMALL              0x104E
#define PMERR_MSGID_TOO_SMALL               0x104F
#define PMERR_NO_HANDLE_ALLOC               0x1050
#define PMERR_NOT_IN_A_PM_SESSION           0x1051
#define PMERR_MSG_QUEUE_ALREADY_EXISTS      0x1052

#endif
#endif

#ifdef INCL_SPLERRORS

#ifndef INCL_SPLERRORS_INCL
#define INCL_SPLERRORS_INCL

#define PMERR_SPL_DRIVER_ERROR             0x4001
#define PMERR_SPL_DEVICE_ERROR             0x4002
#define PMERR_SPL_DEVICE_NOT_INSTALLED     0x4003
#define PMERR_SPL_QUEUE_ERROR              0x4004
#define PMERR_SPL_INV_HSPL                 0x4005
#define PMERR_SPL_NO_DISK_SPACE            0x4006
#define PMERR_SPL_NO_MEMORY                0x4007
#define PMERR_SPL_PRINT_ABORT              0x4008
#define PMERR_SPL_SPOOLER_NOT_INSTALLED    0x4009
#define PMERR_SPL_INV_FORMS_CODE           0x400A
#define PMERR_SPL_INV_PRIORITY             0x400B
#define PMERR_SPL_NO_FREE_JOB_ID           0x400C
#define PMERR_SPL_NO_DATA                  0x400D
#define PMERR_SPL_INV_TOKEN                0x400E
#define PMERR_SPL_INV_DATATYPE             0x400F
#define PMERR_SPL_PROCESSOR_ERROR          0x4010
#define PMERR_SPL_INV_JOB_ID               0x4011
#define PMERR_SPL_JOB_NOT_PRINTING         0x4012
#define PMERR_SPL_JOB_PRINTING             0x4013
#define PMERR_SPL_QUEUE_ALREADY_EXISTS     0x4014
#define PMERR_SPL_INV_QUEUE_NAME           0x4015
#define PMERR_SPL_QUEUE_NOT_EMPTY          0x4016
#define PMERR_SPL_DEVICE_ALREADY_EXISTS    0x4017
#define PMERR_SPL_DEVICE_LIMIT_REACHED     0x4018
#define PMERR_SPL_STATUS_STRING_TRUNC      0x4019
#define PMERR_SPL_INV_LENGTH_OR_COUNT      0x401A
#define PMERR_SPL_FILE_NOT_FOUND           0x401B
#define PMERR_SPL_CANNOT_OPEN_FILE         0x401C
#define PMERR_SPL_DRIVER_NOT_INSTALLED     0x401D
#define PMERR_SPL_INV_PROCESSOR_DATTYPE    0x401E
#define PMERR_SPL_INV_DRIVER_DATATYPE      0x401F
#define PMERR_SPL_PROCESSOR_NOT_INST       0x4020
#define PMERR_SPL_NO_SUCH_LOG_ADDRESS      0x4021
#define PMERR_SPL_PRINTER_NOT_FOUND        0x4022
#define PMERR_SPL_DD_NOT_FOUND             0x4023
#define PMERR_SPL_QUEUE_NOT_FOUND          0x4024
#define PMERR_SPL_MANY_QUEUES_ASSOC        0x4025
#define PMERR_SPL_NO_QUEUES_ASSOCIATED     0x4026
#define PMERR_SPL_INI_FILE_ERROR           0x4027
#define PMERR_SPL_NO_DEFAULT_QUEUE         0x4028
#define PMERR_SPL_NO_CURRENT_FORMS_CODE    0x4029
#define PMERR_SPL_NOT_AUTHORISED           0x402A
#define PMERR_SPL_TEMP_NETWORK_ERROR       0x402B
#define PMERR_SPL_HARD_NETWORK_ERROR       0x402C
#define PMERR_DEL_NOT_ALLOWED              0x402D
#define PMERR_CANNOT_DEL_QP_REF            0x402E
#define PMERR_CANNOT_DEL_QNAME_REF         0x402F
#define PMERR_CANNOT_DEL_PRINTER_DD_REF    0x4030
#define PMERR_CANNOT_DEL_PRN_NAME_REF      0x4031
#define PMERR_CANNOT_DEL_PRN_ADDR_REF      0x4032
#define PMERR_SPOOLER_QP_NOT_DEFINED       0x4033
#define PMERR_PRN_NAME_NOT_DEFINED         0x4034
#define PMERR_PRN_ADDR_NOT_DEFINED         0x4035
#define PMERR_PRINTER_DD_NOT_DEFINED       0x4036
#define PMERR_PRINTER_QUEUE_NOT_DEFINED    0x4037
#define PMERR_PRN_ADDR_IN_USE              0x4038
#define PMERR_SPL_TOO_MANY_OPEN_FILES      0x4039
#define PMERR_SPL_CP_NOT_REQD              0x403A
#define PMERR_SPL_PORT_SHUTDOWN            0x403B
#define PMERR_SPL_NOT_HANDLED              0x403C
#define PMERR_SPL_CNV_NOT_INIT             0x403D
#define PMERR_SPL_INIT_IN_PROGRESS         0x403E
#define PMERR_SPL_TYPE_NOT_AVAIL           0x403F
#define PMERR_UNABLE_TO_CLOSE_DEVICE       0x4040
#define PMERR_SPL_SESSION_TERM             0x4041
#define PMERR_SPL_NOT_REGISTERED           0x4042

#define PMERR_SPL_ERROR_1  (SPLERR_BASE+4001)
#define PMERR_SPL_ERROR_2  (SPLERR_BASE+4002)
#define PMERR_SPL_ERROR_3  (SPLERR_BASE+4003)
#define PMERR_SPL_ERROR_4  (SPLERR_BASE+4004)
#define PMERR_SPL_ERROR_5  (SPLERR_BASE+4005)
#define PMERR_SPL_ERROR_6  (SPLERR_BASE+4006)
#define PMERR_SPL_ERROR_7  (SPLERR_BASE+4007)
#define PMERR_SPL_ERROR_8  (SPLERR_BASE+4008)
#define PMERR_SPL_ERROR_9  (SPLERR_BASE+4009)
#define PMERR_SPL_ERROR_10 (SPLERR_BASE+4010)
#define PMERR_SPL_ERROR_11 (SPLERR_BASE+4011)
#define PMERR_SPL_ERROR_12 (SPLERR_BASE+4012)
#define PMERR_SPL_ERROR_13 (SPLERR_BASE+4013)
#define PMERR_SPL_ERROR_14 (SPLERR_BASE+4014)
#define PMERR_SPL_ERROR_15 (SPLERR_BASE+4015)
#define PMERR_SPL_ERROR_16 (SPLERR_BASE+4016)
#define PMERR_SPL_ERROR_17 (SPLERR_BASE+4017)
#define PMERR_SPL_ERROR_18 (SPLERR_BASE+4018)
#define PMERR_SPL_ERROR_19 (SPLERR_BASE+4019)
#define PMERR_SPL_ERROR_20 (SPLERR_BASE+4020)
#define PMERR_SPL_ERROR_21 (SPLERR_BASE+4021)
#define PMERR_SPL_ERROR_22 (SPLERR_BASE+4022)
#define PMERR_SPL_ERROR_23 (SPLERR_BASE+4023)
#define PMERR_SPL_ERROR_24 (SPLERR_BASE+4024)
#define PMERR_SPL_ERROR_25 (SPLERR_BASE+4025)
#define PMERR_SPL_ERROR_26 (SPLERR_BASE+4026)
#define PMERR_SPL_ERROR_27 (SPLERR_BASE+4027)
#define PMERR_SPL_ERROR_28 (SPLERR_BASE+4028)
#define PMERR_SPL_ERROR_29 (SPLERR_BASE+4029)
#define PMERR_SPL_ERROR_30 (SPLERR_BASE+4030)
#define PMERR_SPL_ERROR_31 (SPLERR_BASE+4031)
#define PMERR_SPL_ERROR_32 (SPLERR_BASE+4032)
#define PMERR_SPL_ERROR_33 (SPLERR_BASE+4033)
#define PMERR_SPL_ERROR_34 (SPLERR_BASE+4034)
#define PMERR_SPL_ERROR_35 (SPLERR_BASE+4035)
#define PMERR_SPL_ERROR_36 (SPLERR_BASE+4036)
#define PMERR_SPL_ERROR_37 (SPLERR_BASE+4037)
#define PMERR_SPL_ERROR_38 (SPLERR_BASE+4038)
#define PMERR_SPL_ERROR_39 (SPLERR_BASE+4039)
#define PMERR_SPL_ERROR_40 (SPLERR_BASE+4040)

#define PMERR_SPLMSGBOX_INFO_CAPTION    (SPLERR_BASE+4041)
#define PMERR_SPLMSGBOX_WARNING_CAPTION (SPLERR_BASE+4042)
#define PMERR_SPLMSGBOX_ERROR_CAPTION   (SPLERR_BASE+4043)
#define PMERR_SPLMSGBOX_SEVERE_CAPTION  (SPLERR_BASE+4044)
#define PMERR_SPLMSGBOX_JOB_DETAILS     (SPLERR_BASE+4045)
#define PMERR_SPLMSGBOX_ERROR_ACTION    (SPLERR_BASE+4046)
#define PMERR_SPLMSGBOX_SEVERE_ACTION   (SPLERR_BASE+4047)
#define PMERR_SPLMSGBOX_BIT_0_TEXT      (SPLERR_BASE+4048)
#define PMERR_SPLMSGBOX_BIT_1_TEXT      (SPLERR_BASE+4049)
#define PMERR_SPLMSGBOX_BIT_2_TEXT      (SPLERR_BASE+4050)
#define PMERR_SPLMSGBOX_BIT_3_TEXT      (SPLERR_BASE+4051)
#define PMERR_SPLMSGBOX_BIT_4_TEXT      (SPLERR_BASE+4052)
#define PMERR_SPLMSGBOX_BIT_5_TEXT      (SPLERR_BASE+4053)
#define PMERR_SPLMSGBOX_BIT_15_TEXT     (SPLERR_BASE+4054)
#define PMERR_SPL_NOPATHBUFFER          (SPLERR_BASE+4055)
#define PMERR_SPL_ALREADY_INITIALISED   (SPLERR_BASE+4093)
#define PMERR_SPL_ERROR                 (SPLERR_BASE+4095)

#define NERR_BASE             2100
#define NERR_NetNotStarted    (NERR_BASE+2)
#define NERR_RedirectedPath   (NERR_BASE+17)
#define NERR_BufTooSmall      (NERR_BASE+23)
#define NERR_InvalidAPI       (NERR_BASE+42)
#define NERR_QNotFound        (NERR_BASE+50)
#define NERR_JobNotFound      (NERR_BASE+51)
#define NERR_DestNotFound     (NERR_BASE+52)
#define NERR_DestExists       (NERR_BASE+53)
#define NERR_QExists          (NERR_BASE+54)
#define NERR_QNoRoom          (NERR_BASE+55)
#define NERR_JobNoRoom        (NERR_BASE+56)
#define NERR_DestNoRoom       (NERR_BASE+57)
#define NERR_DestIdle         (NERR_BASE+58)
#define NERR_DestInvalidOp    (NERR_BASE+59)
#define NERR_SpoolerNotLoaded (NERR_BASE+61)
#define NERR_DestInvalidState (NERR_BASE+62)
#define NERR_JobInvalidState  (NERR_BASE+64)
#define NERR_SpoolNoMemory    (NERR_BASE+65)
#define NERR_DriverNotFound   (NERR_BASE+66)
#define NERR_DataTypeInvalid  (NERR_BASE+67)
#define NERR_ProcNotFound     (NERR_BASE+68)
#define NERR_BadDev           (NERR_BASE+241)
#define NERR_CommDevInUse     (NERR_BASE+243)
#define NERR_InvalidComputer  (NERR_BASE+251)
#define NERR_OpenFiles        (NERR_BASE+301)
#define NERR_LocalDrive       (NERR_BASE+305)

#endif
#endif

