#pmake: all build compact cpu_i86 os_win
#
# plibc -- 16-bit compact memory-model PLIB for Windows
#
processor  = i86
system     = windows
model      = c
linkage    = static
define_library_include = $(plusplus_runtime_dir)/plib.mif
!include $(plusplus_dir)/mklib.mif
