#pmake: all build large cpu_i86 os_os2
#
# strgmtl.lib -- large memory-model multi-thread STRING library
#
processor  = i86
system     = os2
model      = l
convention =
linkage    = static
mthreaded  = 1
define_library_include = $(plusplus_string_dir)/string.mif
define_deps_include = $(plusplus_string_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
