#pmake: all build medium cpu_i86 os_win
processor  = i86
system     = windows
model      = m
linkage    = static
subdir     = wbcsd
define_library_include = $(plusplus_cpplib_dir)/plib.mif
!include $(plusplus_dir)/mrglib.mif
