#pmake: build compact cpu_i86 os_win
#
# iostc.lib -- compact memory-model IOSTREAM library for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static
define_library_include = $(plusplus_iostream_dir)/iostream.mif
define_deps_include = $(plusplus_iostream_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
