#pmake: build medium cpu_i86 os_osi
#
# cplxm.lib -- medium memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mm
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(cpplib_dir)/mklib.mif
