#pmake: all build medium cpu_i86 os_osi
#
# cplxm.lib -- medium memory-model COMPLEX library fpc
#
processor  = i86
system     = generic
model      = m
linkage    = static
define_library_include = $(plusplus_complex_dir)/complex.mif
define_deps_include = $(plusplus_complex_dir)/deps.mif
!include $(plusplus_dir)/mklib.mif
