
objs = &
allign &
datamix1 &
datamix2 &
jmpshrt &
mseg &
opi8u &
plsintr &
proccall &
segatrep &
shift &
structdd &
testequ

dev_objs = &
irpexitm &
lea &
lsxxx &
retiret &
seg16

!include ../test.mif
