#pmake: build os_nt cpu_386

host_OS             = nt

proj_name           = base
include_dir         = ../include
root_include_dir    = ../include
lib_dir             = ../lib
what_to_build       = headers

!include ../master.mif
