#pmake: build serv remote os_linux cpu_386 par
host_CPU = 386
host_OS = linux

os = linux
srv = par
cpu = x86
which = SERVER

extra_objs = $(remote_objs) parlinux.obj peloader.obj

!include $(trap_dir)/master.mif

