#pmake: all build cpu_i86 os_win
op_sys=windows dll libfile libentry.obj
os=windows
ccopt = -zw -ml -zu -bd -d__DLL__
name=pbide
compiler=wcc
objs = pbide.obj errdll.obj
libs = ddeml.lib
ext = dll

!include ..\mif\master.mif
