#pmake: build os_qnx cpu_386
# makefile for GRAPH3R.LIB

libname =       graph3s
model =         -ms -3s -d_SUPERVGA -bt=QNX -d__STACK
module =        $[&s
module =        $[&
cdecl =
fard =
_386 =          386
_qnx =          q
asm_cmd =       wasm
asm_flags =     -zq -3s -ms -i..\inc\ -d_QNX -d_MODEL=_SMALL -d_386

!include ../graphics.mif
