
objs = &
387 &
a &
alias &
alignorg &
anon &
anthony &
b &
backquot &
bar &
beep &
bigext &
bug &
#bunk &
c &
cmps &
comm &
current &
data &
diag01 &
diag02 &
diag03 &
dos16m &
dosinite &
dosstart &
do_ax &
dup &
empty &
error &
f &
farjmp &
fcom &
five &
float &
foo &
g &
getenv &
hello &
ifs &
include &
ins &
irp &
jmpext &
jmpfword &
jmpsize &
jmptst &
#kyb &
l2 &
l3 &
labelbug &
lods &
maaak &
macro &
macroloc &
macrotst &
main &
mainnew &
mangle &
masmsuks &
masmtest &
movs &
new &
newbug &
newmif &
newproc &
notcomm &
offset &
org &
orgage &
outs &
passtest &
proc &
proc3 &
pub &
pub2 &
pubdef &
q &
qnxstrt &
quote &
scas &
segoff &
shell &
size &
sizebug &
sizebug2 &
stos &
strmang &
struct &
structjn &
t2 &
test &
tmp &
tn &
wincall &
word &
x &
xx

dev_objs = &
fubar &
jmp &
loader2

asm_flags_x = -c
asm_flags_diag01 = -4s
asm_flags_diag02 = -3
asm_flags_diag03 = -wx
asm_flags_getenv = -I"$(watcom_dir)/h"

!include ../test.mif
